'use client';
import React,{useRef,useState,useId} from 'react';
import {CalendarDays} from 'lucide-react';
import {Input as PlainInput} from '../ui/input';
import {WheelPicker} from '../motion/wheel-picker';
import {Button} from '../ui/button';
import {tr,getLanguage} from '@/lib/i18n';
const pad=(n:number)=>String(n).padStart(2,'0');
export function DateWheelInput({value,defaultValue,onChange,ref,...props}:React.ComponentProps<'input'>){
 const [internal,setInternal]=useState(String(defaultValue||''));const current=value===undefined?internal:String(value);const input=useRef<HTMLInputElement>(null);const dialog=useRef<HTMLDialogElement>(null);const heading=useId();const [draft,setDraft]=useState('');
 const parts=(draft||'2000-01-01T09:00').split(/[-T:]/).map(Number);const [year,month,day,hour=9,minute=0]=parts;const days=new Date(year,month,0).getDate();
 const birthday=props.name==='birthDate';const today=new Date();const minYear=birthday?today.getFullYear()-120:today.getFullYear()-5;const maxYear=birthday?today.getFullYear():today.getFullYear()+10;
 function change(index:number,v:string){const p=[year,month,day,hour,minute];p[index]=Number(v);p[2]=Math.min(p[2],new Date(p[0],p[1],0).getDate());setDraft(`${p[0]}-${pad(p[1])}-${pad(p[2])}T${pad(p[3])}:${pad(p[4])}`)}
 function commit(){const next=props.type==='date'?draft.slice(0,10):draft;const node=input.current!;const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!;setter.call(node,next);node.dispatchEvent(new Event('input',{bubbles:true}));node.dispatchEvent(new Event('change',{bubbles:true}));if(node.checkValidity())dialog.current?.close();else node.reportValidity();}
 const options=(count:number,start=0)=>Array.from({length:count},(_,i)=>({value:String(i+start),label:pad(i+start)}));
 return <div className="silver-date"><div className="silver-date-control"><PlainInput {...props} className={birthday?'date-value-native':props.className} tabIndex={birthday?-1:props.tabIndex} onInvalid={e=>{props.onInvalid?.(e);if(birthday){e.preventDefault();setDraft((current||`${today.getFullYear()-18}-01-01`)+'T09:00');dialog.current?.showModal()}}} value={current} ref={node=>{input.current=node;if(typeof ref==='function')ref(node);else if(ref)ref.current=node}} onChange={e=>{setInternal(e.target.value);onChange?.(e)}}/><button type="button" className={birthday?"date-wheel-open date-birthday-open":"date-wheel-open"} aria-label={birthday?`${tr('Date of birth')}: ${current||tr('Choose date and time')}`:tr('Choose date and time')} disabled={props.disabled} onClick={()=>{const d=current||`${birthday?today.getFullYear()-18:today.getFullYear()}-${pad(today.getMonth()+1)}-${pad(today.getDate())}T09:00`;setDraft(d.includes('T')?d:d+'T09:00');dialog.current?.showModal()}}>{birthday&&<span>{current?new Intl.DateTimeFormat(getLanguage(),{day:'numeric',month:'short',year:'numeric'}).format(new Date(current+'T12:00:00')):tr('Date of birth')}</span>}<CalendarDays/></button></div>
 <dialog ref={dialog} className="silver-wheel-dialog" aria-labelledby={heading}><h2 id={heading}>{tr(birthday?'Date of birth':'Choose date and time')}</h2><div className="date-wheels"><WheelPicker aria-label={tr('Day')} options={options(days,1)} value={String(day)} onValueChange={v=>change(2,v)} itemHeight={44}/><WheelPicker aria-label={tr('Month')} options={Array.from({length:12},(_,i)=>({value:String(i+1),label:new Intl.DateTimeFormat(getLanguage(),{month:'short'}).format(new Date(2000,i,1))}))} value={String(month)} onValueChange={v=>change(1,v)} itemHeight={44}/><WheelPicker aria-label={tr('Year')} options={Array.from({length:maxYear-minYear+1},(_,i)=>String(minYear+i))} value={String(year)} onValueChange={v=>change(0,v)} itemHeight={44}/></div>{props.type==='datetime-local'&&<div className="time-wheels"><WheelPicker aria-label={tr('Hour')} options={options(24)} value={String(hour)} onValueChange={v=>change(3,v)} itemHeight={44}/><span>:</span><WheelPicker aria-label={tr('Minute')} options={options(60)} value={String(minute)} onValueChange={v=>change(4,v)} itemHeight={44}/></div>}<div className="wheel-actions"><Button type="button" variant="outline" onClick={()=>dialog.current?.close()}>{tr('Cancel')}</Button><Button type="button" onClick={commit}>{tr('Done')}</Button></div></dialog></div>;
}
