'use client';
import React,{useRef,useState,useEffect} from 'react';
import {Select,SelectTrigger,SelectContent,SelectItem} from '../motion/select';
import {tr} from '@/lib/i18n';
export function NativeSelect({children,value,defaultValue,onChange,className,size,ref,...props}:Omit<React.ComponentProps<'select'>,'size'>&{size?:string}){
 const [internal,setInternal]=useState(String(defaultValue??'')),[open,setOpen]=useState(false),[query,setQuery]=useState('');const native=useRef<HTMLSelectElement>(null),root=useRef<HTMLDivElement>(null);const current=String(value??internal);
 const options:{value:string,label:string,disabled?:boolean}[]=[];
 function collect(nodes:React.ReactNode){React.Children.forEach(nodes,c=>{if(!React.isValidElement(c))return;const p=c.props as any;if(c.type==='option')options.push({value:String(p.value??p.children),label:React.Children.toArray(p.children).join(''),disabled:p.disabled});else if(p.children)collect(p.children)})}collect(children);
 const selected=options.findIndex(o=>o.value===current);const shown=options.map((o,i)=>({...o,id:String(i)})).filter(o=>!query||o.label.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 function choose(id:string){const option=options[Number(id)];if(!option)return;setInternal(option.value);const node=native.current!;Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype,'value')!.set!.call(node,option.value);node.dispatchEvent(new Event('change',{bubbles:true}));setOpen(false);root.current?.querySelector<HTMLButtonElement>('[aria-haspopup]')?.focus();}
 useEffect(()=>{if(!open)return;const timer=setTimeout(()=>root.current?.querySelector<HTMLInputElement>('.select-search')?.focus(),50);return()=>clearTimeout(timer)},[open]);
 return <div ref={root} className={'silver-select '+(open?'is-open ':'')+(className||'')} onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);root.current?.querySelector<HTMLButtonElement>('[aria-haspopup]')?.focus()}if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();if(!open){setOpen(true);return}const choices=Array.from(root.current?.querySelectorAll<HTMLButtonElement>('[role=option]:not(:disabled)')||[]);const index=choices.indexOf(document.activeElement as HTMLButtonElement);const next=e.key==='Home'?0:e.key==='End'?choices.length-1:Math.max(0,Math.min(choices.length-1,index+(e.key==='ArrowDown'?1:-1)));choices[next]?.focus()}}}>
 <select {...props} ref={node=>{native.current=node;if(typeof ref==='function')ref(node);else if(ref)ref.current=node}} tabIndex={-1} aria-hidden="true" className="select-form-control" value={current} onChange={e=>{setInternal(e.target.value);onChange?.(e)}} onInvalid={e=>{e.preventDefault();setOpen(true);root.current?.querySelector<HTMLButtonElement>('[aria-haspopup]')?.focus()}}>{children}</select>
 <Select value={String(selected)} onValueChange={choose} open={open} onOpenChange={v=>{setOpen(v);setQuery('')}} disabled={props.disabled}><SelectTrigger className="silver-select-trigger"><span>{options[selected]?.label||options[0]?.label||tr('Choose')}</span></SelectTrigger><SelectContent className="silver-select-content">{options.length>8&&<input className="select-search" aria-label={tr('Search options')} placeholder={tr('Search')} value={query} onChange={e=>setQuery(e.target.value)}/>}<ul>{shown.map(o=><SelectItem key={o.id} value={o.id} disabled={o.disabled}>{o.label}</SelectItem>)}</ul>{!shown.length&&<p>{tr('No results')}</p>}</SelectContent></Select></div>;
}
