'use client';
import {useState,useRef,useEffect} from 'react';
import {Send,Mic,Square,Volume2,Plus,Settings2} from 'lucide-react';
import {Button} from './ui/button';
import {Textarea} from './ui/textarea';
import {NativeSelect} from './silver/select';
type Message={role:'user'|'assistant';content:string};
export function CareChat({api,onManual,onSaved,onHealth,preferences,onPreferences}:any){
 const [consent,setConsent]=useState(!!preferences?.ai_consented_at),[messages,setMessages]=useState<Message[]>([]),[text,setText]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [autoSave,setAutoSave]=useState(preferences?.ai_auto_save!==0),[saved,setSaved]=useState<any>(null),[recordError,setRecordError]=useState(false);
 const [voiceSupported,setVoiceSupported]=useState(false),[audioSupported,setAudioSupported]=useState(false),[voiceConsent,setVoiceConsent]=useState(false),[voiceNotice,setVoiceNotice]=useState(false),[listening,setListening]=useState(false),[readAloud,setReadAloud]=useState(true),[speaking,setSpeaking]=useState(false),[lang,setLang]=useState('en-US');
 const recognition=useRef<any>(null),log=useRef<HTMLDivElement>(null),alive=useRef(true),request=useRef<{text:string;id:string}|null>(null);
 useEffect(()=>{alive.current=true;setVoiceSupported(!!((window as any).SpeechRecognition||(window as any).webkitSpeechRecognition));setAudioSupported('speechSynthesis' in window);return()=>{alive.current=false;recognition.current?.abort();window.speechSynthesis?.cancel()}},[]);
 useEffect(()=>{if(log.current)log.current.scrollTop=log.current.scrollHeight},[messages,busy]);
 function stopVoice(){recognition.current?.abort();window.speechSynthesis?.cancel();setListening(false);setSpeaking(false)}
 function speak(content:string){if(!audioSupported)return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(content);u.lang=lang;u.onend=()=>setSpeaking(false);u.onerror=()=>setSpeaking(false);setSpeaking(true);window.speechSynthesis.speak(u)}
 function dictate(){if(listening){recognition.current?.stop();return}if(!voiceConsent){setVoiceNotice(true);return}stopVoice();setError('');const Recognition=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!Recognition){setError('Voice input is unavailable here. Type or use keyboard dictation.');return}const r=new Recognition();recognition.current=r;r.lang=lang;r.continuous=false;r.interimResults=false;r.onresult=(e:any)=>{const words=Array.from(e.results).map((x:any)=>x[0].transcript).join(' ');if(alive.current)setText(t=>(t+' '+words).trim().slice(0,1600))};r.onerror=(e:any)=>{if(alive.current){setListening(false);if(e.error!=='aborted')setError(e.error==='not-allowed'?'Allow microphone access in your browser, or type below.':e.error==='no-speech'?'No speech heard. Tap the microphone to try again.':'Voice input stopped. Try again or type below.')}};r.onend=()=>{if(alive.current)setListening(false)};try{r.start();setListening(true)}catch{setError('Voice input could not start. Type below or try again.')}}
 async function send(e:React.FormEvent){e.preventDefault();if(busy||!text.trim()||!consent)return;stopVoice();setBusy(true);setError('');setSaved(null);setRecordError(false);const content=text.trim();if(request.current?.text!==content)request.current={text:content,id:crypto.randomUUID()};const next:Message[]=[...messages,{role:'user',content}];try{const result=await api('care/chat',{consent:true,autoSavePhysical:autoSave,requestId:request.current.id,messages:next});if(!alive.current)return;setMessages([...next,{role:'assistant',content:result.reply}]);setText('');request.current=null;setSaved(result.record);setRecordError(!!result.recordError);if(result.record)Promise.resolve(onSaved?.()).catch(()=>{});if(readAloud)speak(result.reply)}catch(e:any){if(alive.current)setError(e.message)}finally{if(alive.current)setBusy(false)}}
 async function rememberConsent(value:boolean){setBusy(true);setError('');try{await api('care/ai-consent',{consent:true,autoSavePhysical:value});if(!alive.current)return;setConsent(true);setAutoSave(value);onPreferences?.({ai_consented_at:preferences?.ai_consented_at||Math.floor(Date.now()/1000),ai_auto_save:value?1:0})}catch(e:any){if(alive.current)setError('Could not save your preference. '+e.message)}finally{if(alive.current)setBusy(false)}}
 const full=messages.length>=12;
 return <section className="care-card care-chat care-voice-chat"><div className="care-chat-title"><h2>Let’s talk</h2><div className="care-actions"><Button variant="ghost" disabled={busy||listening||!!text.trim()} onClick={()=>{stopVoice();setMessages([]);setSaved(null);setRecordError(false);setError('');request.current=null}}><Plus size={18}/>New conversation</Button><Button variant="ghost" onClick={onManual} disabled={busy||listening}>Write a record</Button></div></div>
 {!consent&&<div className="care-chat-consent"><h3>Before we start</h3><p>Your messages go to Groq for AI replies. AI can make mistakes and cannot diagnose.</p><label className="care-check"><input type="checkbox" checked={autoSave} onChange={e=>setAutoSave(e.target.checked)}/>Save my physical concerns to My Health</label><p className="care-muted">AI selects your original words. Emotional-only conversations are not added. You can edit or delete any saved note. Groq may retain messages for reliability or abuse checks.</p><a href="https://console.groq.com/docs/your-data" target="_blank" rel="noreferrer">Privacy details</a><Button disabled={busy} onClick={()=>rememberConsent(autoSave)}>{busy?'Saving…':'Agree and start'}</Button></div>}
 {error&&<p className="error" role="alert">{error}</p>}
 <div className="care-mic-stage"><button className={'care-big-mic'+(listening?' is-listening':'')+(speaking?' is-speaking':'')} onClick={speaking?stopVoice:dictate} disabled={!consent||busy||full||!voiceSupported} aria-label={speaking?'Stop spoken reply':listening?'Stop microphone':'Start voice conversation'} aria-pressed={listening}>{listening||speaking?<Square size={54}/>:<Mic size={64}/>}</button><h3 aria-live="polite">{busy?'Thinking…':listening?'I’m listening':speaking?'Silver Care is speaking':full?'Ready for a new conversation?':'How are you feeling?'}</h3><p>{listening?'Tap to stop, then send your words.':!voiceSupported?'Type below or use your keyboard’s dictation.':'Tap the microphone to speak'}</p></div>
 {consent&&<><details className="care-voice-settings"><summary><Settings2 size={18}/>Conversation options</summary><div className="care-voice-tools"><label>Language<NativeSelect value={lang} disabled={listening} onChange={e=>setLang(e.target.value)}><option value="en-US">English</option><option value="zh-HK">Cantonese</option><option value="zh-CN">Mandarin</option></NativeSelect></label>{audioSupported&&<label className="care-check"><input type="checkbox" checked={readAloud} onChange={e=>{setReadAloud(e.target.checked);if(!e.target.checked)stopVoice()}}/>Read replies aloud</label>}<label className="care-check"><input type="checkbox" checked={autoSave} disabled={busy} onChange={e=>rememberConsent(e.target.checked)}/>Save physical concerns to My Health</label></div></details>
 {voiceNotice&&<div className="care-empty"><p>Your browser may send audio to its speech service. Review the transcript before sending.</p><Button onClick={()=>{setVoiceConsent(true);setVoiceNotice(false)}}>Enable microphone</Button><Button variant="ghost" onClick={()=>setVoiceNotice(false)}>Cancel</Button></div>}
 {messages.length>0&&<div ref={log} className="care-chat-log" role="log" aria-label="Current conversation" aria-live="polite">{messages.map((m,i)=><div key={i} className={'care-bubble '+m.role}><small>{m.role==='user'?'You':'Silver Care · AI'}</small><p>{m.content}</p>{m.role==='assistant'&&audioSupported&&<Button variant="ghost" aria-label="Listen to reply" onClick={()=>speak(m.content)}><Volume2 size={17}/>Listen</Button>}</div>)}</div>}
 {saved&&<div className="care-auto-note" role="status"><strong>Added to My Health</strong><p>“{saved.description}”</p><Button variant="link" onClick={onHealth}>View or edit note</Button></div>}{recordError&&<p className="error" role="alert">Your reply arrived, but the health note could not be saved. Use “Write a record” to keep it.</p>}

 <form onSubmit={send} className="care-chat-compose"><Textarea aria-label="Message Silver Care" placeholder="Or type a message…" value={text} onChange={e=>setText(e.target.value)} maxLength={1600} disabled={busy||full||listening} required/><Button type="submit" disabled={busy||full||listening||!text.trim()} aria-label="Send message"><Send size={24}/></Button></form><p className="care-chat-footnote">{full?'Choose New conversation to continue.':'AI is not emergency support. In Hong Kong, call 999 for emergencies.'}</p></>}
 </section>;
}
