'use client';
import {useState,useRef,useEffect} from 'react';
import {MessageCircle,Send,ArrowRight,Mic,Square,Volume2,Plus} from 'lucide-react';
import {Button} from './ui/button';
import {Textarea} from './ui/textarea';
import {NativeSelect} from './silver/select';
type Message={role:'user'|'assistant';content:string};
export function CareChat({api,onDraft,onManual}:any){
 const [consent,setConsent]=useState(false),[messages,setMessages]=useState<Message[]>([]),[text,setText]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [history,setHistory]=useState<any[]>([]),[historyLoading,setHistoryLoading]=useState(true),[current,setCurrent]=useState<{id:string;version:number}|null>(null),[unsaved,setUnsaved]=useState(false);
 const [voiceSupported,setVoiceSupported]=useState(false),[audioSupported,setAudioSupported]=useState(false),[voiceConsent,setVoiceConsent]=useState(false),[voiceNotice,setVoiceNotice]=useState(false),[listening,setListening]=useState(false),[readAloud,setReadAloud]=useState(false),[speaking,setSpeaking]=useState(false),[lang,setLang]=useState('en-US');
 const recognition=useRef<any>(null),log=useRef<HTMLDivElement>(null),alive=useRef(true);
 const refresh=async()=>{const r=await api('care/conversations');if(alive.current)setHistory(r.conversations)};
 useEffect(()=>{alive.current=true;setVoiceSupported(!!((window as any).SpeechRecognition||(window as any).webkitSpeechRecognition));setAudioSupported('speechSynthesis' in window);refresh().catch((e:any)=>setError(e.message)).finally(()=>setHistoryLoading(false));return()=>{alive.current=false;recognition.current?.abort();window.speechSynthesis?.cancel()}},[]);
 useEffect(()=>{if(log.current)log.current.scrollTop=log.current.scrollHeight},[messages,busy]);
 function stopVoice(){recognition.current?.abort();window.speechSynthesis?.cancel();setListening(false);setSpeaking(false)}
 function speak(content:string){if(!audioSupported)return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(content);u.lang=lang;u.onend=()=>setSpeaking(false);u.onerror=()=>setSpeaking(false);setSpeaking(true);window.speechSynthesis.speak(u)}
 function dictate(){if(listening){recognition.current?.stop();return}if(!voiceConsent){setVoiceNotice(true);return}stopVoice();setError('');const Recognition=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!Recognition){setError('Voice input is unavailable in this browser. You can type instead.');return}const r=new Recognition();recognition.current=r;r.lang=lang;r.continuous=false;r.interimResults=false;r.onresult=(e:any)=>{const words=Array.from(e.results).map((x:any)=>x[0].transcript).join(' ');if(alive.current)setText(t=>(t+' '+words).trim().slice(0,1600))};r.onerror=(e:any)=>{if(alive.current){setListening(false);if(e.error!=='aborted')setError(e.error==='not-allowed'?'Microphone permission was denied. You can type instead.':'Voice input stopped. Try again or type your message.')}};r.onend=()=>{if(alive.current)setListening(false)};try{r.start();setListening(true)}catch{setError('Voice input could not start. Try again or type instead.')}}
 async function persist(next:Message[]){setUnsaved(true);const r=await api('care/save-conversation',{...(current||{}),consent:true,messages:next});if(!alive.current)return;setCurrent(r);setUnsaved(false);await refresh()}
 async function send(e:React.FormEvent){e.preventDefault();if(busy||unsaved||!text.trim()||!consent)return;stopVoice();setBusy(true);setError('');const next:Message[]=[...messages,{role:'user',content:text.trim()}];try{const result=await api('care/chat',{consent:true,messages:next});if(!alive.current)return;const complete:Message[]=[...next,{role:'assistant',content:result.reply}];setMessages(complete);setText('');try{await persist(complete)}catch{setError('Your reply arrived, but this chat could not be saved. Retry saving before leaving.')}if(readAloud)speak(result.reply)}catch(e:any){if(alive.current)setError(e.message)}finally{if(alive.current)setBusy(false)}}
 async function open(c:any){stopVoice();setBusy(true);setError('');try{const r=await api('care/conversation?id='+encodeURIComponent(c.id));setMessages(r.messages);setCurrent({id:r.id,version:r.version});setText('');setConsent(false)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 const full=messages.length>=12;
 return <div className="care-conversation-layout"><aside className="care-chat-history"><Button disabled={busy||unsaved||!!text.trim()} onClick={()=>{stopVoice();setCurrent(null);setMessages([]);setText('');setError('');setConsent(false)}}><Plus size={18}/>New chat</Button><h2>Conversations</h2>{historyLoading?<p role="status">Loading chats…</p>:!history.length?<p className="care-muted">Your saved chats appear here.</p>:history.map(c=><button className={current?.id===c.id?'is-current':''} key={c.id} disabled={busy||unsaved||!!text.trim()} onClick={()=>open(c)}><span>{c.title}</span><small>{new Date(c.updated_at*1000).toLocaleDateString()}</small></button>)}{current&&<details><summary>Delete this chat</summary><p>Permanently remove this conversation?</p><Button variant="outline" disabled={busy||unsaved} onClick={async()=>{setBusy(true);try{await api('care/delete-conversation',{id:current.id});stopVoice();setCurrent(null);setMessages([]);setConsent(false);await refresh()}catch(e:any){setError(e.message)}finally{setBusy(false)}}}>Confirm deletion</Button></details>}</aside>
 <section className="care-card care-chat"><div className="care-chat-title"><div><MessageCircle/><h2>Let’s talk</h2></div><Button variant="ghost" onClick={onManual} disabled={busy||unsaved||!!text.trim()}>Write a record</Button></div>
 {messages.length>0&&<div ref={log} className="care-chat-log" role="log" aria-label="Conversation" aria-live="polite">{messages.map((m,i)=><div key={i} className={'care-bubble '+m.role}><small>{m.role==='user'?'You':'Silver Care · AI'}</small><p>{m.content}</p>{m.role==='assistant'&&audioSupported&&<Button variant="ghost" aria-label="Listen to reply" onClick={()=>speak(m.content)}><Volume2 size={17}/>Listen</Button>}</div>)}{busy&&<p role="status">Silver Care is thinking…</p>}</div>}
 {!consent?<div className="care-chat-consent"><h3>{messages.length?'Continue this conversation':'Before we chat'}</h3><p>Your conversation is sent to Groq for AI replies and saved privately in Silver Care. Only this conversation is sent, not your other records or contacts.</p><p>Groq may retain content for reliability or abuse checks. AI can make mistakes and cannot diagnose or prescribe.</p><a href="https://console.groq.com/docs/your-data" target="_blank" rel="noreferrer">Groq privacy details</a><Button onClick={()=>setConsent(true)}>Agree and {messages.length?'continue':'start chat'}</Button></div>:<>
 {!messages.length&&<div className="care-chat-welcome"><h3>How are you feeling?</h3><p>Type a message or use your voice.</p></div>}
 <div className="care-voice-tools"><label>Voice language<NativeSelect value={lang} disabled={listening} onChange={e=>setLang(e.target.value)}><option value="en-US">English</option><option value="zh-HK">Cantonese</option><option value="zh-CN">Mandarin</option></NativeSelect></label>{audioSupported&&<label className="care-check"><input type="checkbox" checked={readAloud} onChange={e=>{setReadAloud(e.target.checked);if(!e.target.checked){window.speechSynthesis.cancel();setSpeaking(false)}}}/>Read replies aloud</label>}{speaking&&<Button variant="outline" onClick={stopVoice}><Square size={16}/>Stop audio</Button>}</div>
 {voiceNotice&&<div className="care-empty"><p>Your browser may send microphone audio to its speech service. Silver Care saves the transcript, not audio. Review the text before sending.</p><Button onClick={()=>{setVoiceConsent(true);setVoiceNotice(false)}}>Enable voice input</Button><Button variant="ghost" onClick={()=>setVoiceNotice(false)}>Cancel</Button></div>}
 <form onSubmit={send} className="care-chat-compose"><Textarea aria-label="Message Silver Care" placeholder="Tell me how you feel…" value={text} onChange={e=>setText(e.target.value)} maxLength={1600} disabled={busy||full||unsaved||listening} required/>{voiceSupported&&<Button type="button" variant="outline" disabled={busy||full||unsaved} onClick={dictate} aria-label={listening?'Stop microphone':'Use microphone'}>{listening?<Square size={20}/>:<Mic size={20}/>}</Button>}<Button type="submit" disabled={busy||full||unsaved||listening||!text.trim()} aria-label="Send message"><Send size={20}/></Button></form>
 {listening&&<p role="status">Listening… Stop when you are ready, then send your message.</p>}{!voiceSupported&&<p className="care-muted">Voice input is unavailable in this browser. Type or use your keyboard’s dictation.</p>}
 <p className="care-muted">{full?'This conversation is complete. Start a new chat to keep talking.':'AI can make mistakes. For emergencies in Hong Kong, call 999.'}</p>
 <div className="care-actions">{messages.some(m=>m.role==='user')&&<Button disabled={busy||unsaved} onClick={()=>{stopVoice();onDraft(messages.filter(m=>m.role==='user').map(m=>m.content).join('\n\n'))}}>Review my words <ArrowRight size={18}/></Button>}</div><p className="care-muted">{unsaved?'Chat not saved yet.':messages.length?'Saved privately. Health notes are saved separately after review.':'Your conversation will be saved privately.'}</p>
 </>}{error&&<p className="error" role="alert">{error}</p>}{unsaved&&<Button disabled={busy} onClick={async()=>{setBusy(true);try{await persist(messages);setError('')}catch(e:any){setError(e.message)}finally{setBusy(false)}}}>Retry saving chat</Button>}
 </section></div>;
}
