'use client';
import {useEffect,useState} from 'react';
import {Phone,Plus,Users} from 'lucide-react';
import {Button} from './ui/button';
import {Input} from './ui/input';
export function CareFamily({api}:any){
 const [contacts,setContacts]=useState<any[]>([]),[draft,setDraft]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
 const load=async()=>{const r=await api('care/family');setContacts(r.contacts)};
 useEffect(()=>{load().catch((e:any)=>setError(e.message)).finally(()=>setLoading(false))},[]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await api('care/family-contact',{...draft,phone:draft.phone.replace(/[\s()-]/g,'')});await load();setDraft(null)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <section className="care-card care-family"><div className="care-chat-title"><div><Users/><h2>Your people</h2><p>Keep family a call away.</p></div><Button disabled={busy} onClick={()=>setDraft({name:'',relationship:'',phone:''})}><Plus size={18}/>Add contact</Button></div><p className="care-muted">Contacts stay private. Adding someone does not share your health records.</p>{error&&<p role="alert" className="error">{error}</p>}{loading?<p role="status">Loading contacts…</p>:!contacts.length&&!draft?<p className="care-empty">Add your first family contact.</p>:null}
 {draft&&<form onSubmit={save} className="care-family-form"><fieldset disabled={busy}><label>Name<Input required maxLength={100} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Relationship (optional)<Input maxLength={60} value={draft.relationship} onChange={e=>setDraft({...draft,relationship:e.target.value})}/></label><label>Phone number with country code<Input type="tel" required placeholder="+852 1234 5678" value={draft.phone} onChange={e=>setDraft({...draft,phone:e.target.value})}/></label><div className="care-actions"><Button type="submit">{busy?'Saving…':'Save contact'}</Button><Button type="button" variant="ghost" onClick={()=>setDraft(null)}>Cancel</Button></div></fieldset></form>}
 <div className="care-contact-list">{contacts.map(c=><article key={c.id}><span className="care-contact-avatar" aria-hidden="true">{c.name.slice(0,1).toUpperCase()}</span><div><h3>{c.name}</h3>{c.relationship&&<p>{c.relationship}</p>}<p>{c.phone}</p><div className="care-actions"><Button variant="ghost" onClick={()=>setDraft({id:c.id,version:c.version,name:c.name,relationship:c.relationship,phone:c.phone})}>Edit</Button><details><summary>Remove</summary><p>Remove this contact?</p><Button disabled={busy} variant="outline" onClick={async()=>{setBusy(true);try{await api('care/delete-family-contact',{id:c.id});await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}}>Confirm removal</Button></details></div></div><a className="care-call" href={'tel:'+c.phone} aria-label={'Call '+c.name}><Phone size={19}/>Call</a></article>)}</div><p className="care-muted">Call opens your device’s calling app. A phone service or compatible calling app is required.</p></section>
}
