'use client';
import React,{useEffect,useState} from 'react';
import {motion} from 'motion/react';
import {Home,Users,BookOpen,HeartHandshake,Plus,ShieldCheck,ChartNoAxesCombined,Building2,Clock,Search,ArrowRight} from 'lucide-react';
import {Button} from './ui/button';
import {Input} from './silver/input';
import {NativeSelect} from './silver/select';
import {Textarea} from './ui/textarea';
import {Tabs,TabsList,TabsTrigger} from './motion/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from './ui/dialog';
import {CommunityPicker} from './community-picker';
import {VerificationCenter} from './verification';
import {localizedTime} from '@/lib/i18n';

const time=localizedTime;
const labels:Record<string,string>={training:'Training Program',exchange:'Skill Exchange Program',support:'Community Time Support',community:'Community Program',task:'Verified Community Task'};
const stamp=(n:number)=>n?new Date(n*1000).toLocaleString():'Not scheduled';
export function PartnerForm({children,onSave,label='Save'}:any){const [busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false);return <form onSubmit={async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);setError('');setDone(false);try{await onSave(data);setDone(true)}catch(e:any){setError(e.message)}finally{setBusy(false)}}}><fieldset disabled={busy}>{children}{error&&<p className="error" role="alert">{error}</p>}{done&&<p role="status" className="success">Saved.</p>}<Button type="submit">{busy?'Saving…':label}</Button></fieldset></form>}
export function PartnerField({label,name,value='',type='text',optional=false,...rest}:any){return <label className="field"><span>{label}</span><Input name={name} type={type} defaultValue={value} required={!optional} {...rest}/></label>}
function Text({label,name,value='',optional=false}:any){return <label className="field"><span>{label}</span><Textarea name={name} defaultValue={value} required={!optional} maxLength={8000}/></label>}
function Choice({label,name,value='',children,...rest}:any){return <label className="field"><span>{label}</span><NativeSelect name={name} defaultValue={value} {...rest}>{children}</NativeSelect></label>}
function Blank({children}:any){return <div className="empty"><HeartHandshake/><p>{children}</p></div>}
function Card({children}:any){return <motion.article className="detail-card partner-card" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{duration:.3}}>{children}</motion.article>}
const sections=[['overview','Overview',Home],['needs','Community Needs',Search],['programs','Programs',Users],['training','Training',BookOpen],['tasks','Community Tasks',ShieldCheck],['support','Time Support',HeartHandshake],['participants','Participants',Users],['insights','Insights',ChartNoAxesCombined],['organization','Organization',Building2]] as const;

export function PartnerWorkspace({api,me,nav,refresh,signOut,page='overview'}:any){
 const orgs=me.verification.organizations.filter((o:any)=>o.status==='verified'&&o.review_due>Date.now()/1000);
 const [orgId,setOrgId]=useState(orgs[0]?.id||''),[data,setData]=useState<any>(),[error,setError]=useState(''),[editor,setEditor]=useState<any>(null),[notice,setNotice]=useState('');
 const load=async()=>{if(orgId)setData(await api('partner?organizationId='+encodeURIComponent(orgId)))};
 useEffect(()=>{setData(null);load().catch(e=>setError(e.message));const timer=setInterval(()=>load().catch(e=>setError(e.message)),30000);return()=>clearInterval(timer)},[orgId]);
 const save=async(action:string,b:any)=>{const r=await api('partner/'+action,{...b,organizationId:orgId});await load();setNotice('Your change has been saved.');return r};
 const act=async(action:string,b:any)=>{setError('');try{await save(action,b)}catch(e:any){setError(e.message)}};
 if(!orgId)return <Blank>Current organization verification is required. <Button onClick={()=>nav('verification')}>Open verification</Button></Blank>;
 const canCreate=data&&(data.capabilities.managePrograms||data.capabilities.manageTraining);
 const create=(kind?:string,categoryId?:string)=>setEditor({kind:kind||(data?.capabilities.managePrograms?'community':'training'),category_id:categoryId});
 const current=sections.some(s=>s[0]===page)?page:'overview';
 const summary=data?[
  ['Active programs',data.programs.filter((p:any)=>p.status==='published').length],
  ['Participants',new Set([...data.participants.map((p:any)=>p.user_id),...data.tasks.filter((t:any)=>t.helper_id).map((t:any)=>t.helper_id)]).size],
  ['Completed activities',data.impact.completed],
  ['Time circulated',time(data.impact.circulated)]
 ]:[];
 const programCards=(kind?:string)=>{const list=data.programs.filter((p:any)=>!kind||p.kind===kind);return <div className="partner-grid">{list.map((p:any)=><Card key={p.id}><span className="category">{labels[p.kind]}</span><h2>{p.title}</h2><span className="status">{p.status}</span><p>{p.description}</p>{p.kind==='support'?<p>Fund budget: {time(p.budget)}</p>:p.kind==='task'?<p>{data.tasks.filter((t:any)=>t.program_id===p.id&&t.helper_id).length} / {p.capacity} places matched</p>:<p>{p.enrolled} / {p.capacity} enrolled · {p.completed} completed</p>}{p.requested_at&&<p>{stamp(p.requested_at)}</p>}<div className="partner-actions">{(p.kind==='training'?data.capabilities.manageTraining:data.capabilities.managePrograms)&&<><Button variant="outline" onClick={()=>setEditor(p)}>Edit</Button><Button variant="outline" onClick={()=>act('publish',{id:p.id,version:p.version,publish:p.status!=='published'})}>{p.status==='published'?'Unpublish':'Publish'}</Button></>}</div>{p.kind==='training'&&<small>Skill Badges record community preparation, not a professional qualification.</small>}</Card>)}{!list.length&&<Blank>No {kind?labels[kind].toLowerCase()+'s':'programs'} yet.</Blank>}</div>};
 return <section className="partner-workspace">
 <div className="partner-heading"><div><p className="verification-status"><ShieldCheck size={18}/> {data?.organization.name||'Community Partner'}</p><h1>Community Partner Dashboard</h1></div>{canCreate&&<Button onClick={()=>create()}><Plus/> Create Program</Button>}</div>
 {orgs.length>1&&<Choice label="Organization" value={orgId} onChange={(e:any)=>setOrgId(e.target.value)}>{orgs.map((o:any)=><option key={o.id} value={o.id}>{o.public_name||o.legal_name}</option>)}</Choice>}
 <Tabs value={current} onValueChange={v=>nav('partner/'+v)} variant="pill"><TabsList className="partner-tabs">{sections.map(([key,label,Icon])=><TabsTrigger key={key} value={key}><Icon size={18}/>{label}</TabsTrigger>)}</TabsList></Tabs>
 {error&&<p className="error" role="alert">{error}<Button variant="link" onClick={()=>load().then(()=>setError('')).catch(e=>setError(e.message))}>Try again</Button></p>}{notice&&<p className="success" role="status">{notice}</p>}
 {!data?<p>Loading your organization…</p>:<>
 {current==='overview'&&<><div className="partner-stats">{summary.map(([label,value])=><Card key={label}><p>{label}</p><strong>{value}</strong></Card>)}</div><div className="partner-grid"><Card><h2>Action required</h2><p>{data.participants.filter((e:any)=>e.status==='submitted').length} completion reviews</p>{data.capabilities.managePrograms&&<p>{data.supports.filter((s:any)=>s.status==='pending').length} Time Support requests</p>}<p>{data.tasks.filter((t:any)=>t.status==='awaiting_confirmation').length} tasks awaiting confirmation</p><Button variant="outline" onClick={()=>nav('partner/participants')}>Review participation <ArrowRight/></Button></Card><Card><h2>Community Needs</h2>{data.needs.length?<><p>{data.needs[0].name}</p><strong>{data.needs[0].requests} open requests</strong><p>{data.needs[0].waiting} waiting more than a week</p></>:<p>No open requests at the moment.</p>}<Button variant="outline" onClick={()=>nav('partner/needs')}>Explore needs <ArrowRight/></Button></Card></div><h2>Current programs</h2>{programCards()}</>}
 {current==='needs'&&<><h2>Areas needing support</h2><p>Based on open requests across Silver Bank. These counts describe demand, not a prediction of skills.</p><div className="partner-grid">{data.needs.map((n:any)=><Card key={n.id}><h3>{n.name}</h3><strong>{n.requests} open requests</strong><p>{n.waiting} waiting over seven days</p><div className="partner-actions">{data.capabilities.manageTraining&&<Button variant="outline" onClick={()=>create('training',n.id)}>Create Training</Button>}{data.capabilities.managePrograms&&<Button onClick={()=>create('community',n.id)}>Create Community Program</Button>}</div></Card>)}</div>{!data.needs.length&&<Blank>No unmet requests currently recorded.</Blank>}<h3>Locations with open requests</h3>{data.locations.map((n:any)=><p key={n.location}>{n.location} · {n.requests}</p>)}<h3>Programs with open places</h3>{data.programs.filter((p:any)=>p.status==='published'&&p.enrolled<p.capacity&&p.kind!=='task').map((p:any)=><p key={p.id}>{p.title} · {p.capacity-p.enrolled} places</p>)}{data.capabilities.managePrograms&&<div className="partner-actions"><Button onClick={()=>create('support')}>Create Time Support</Button><Button variant="outline" onClick={()=>create('exchange')}>Create Skill Exchange</Button></div>}</>}
 {current==='programs'&&<><h2>Community & Skill Exchange Programs</h2>{programCards('community')}{programCards('exchange')}<h2>Skill matches</h2>{data.capabilities.managePrograms&&<PartnerForm label="Match participants" onSave={(b:any)=>save('match',b)}><Choice label="Skill Exchange Program" name="programId">{data.programs.filter((p:any)=>p.kind==='exchange').map((p:any)=><option key={p.id} value={p.id}>{p.title}</option>)}</Choice><Choice name="sharerId" label="Skill sharer"><option value="">Choose a participant</option>{data.participants.filter((e:any)=>e.kind==='exchange'&&['sharer','both'].includes(e.role)&&!['withdrawn','declined'].includes(e.status)).map((e:any)=><option key={e.id} value={e.user_id}>{e.name} · {e.title}</option>)}</Choice><Choice name="learnerId" label="Skill learner"><option value="">Choose a participant</option>{data.participants.filter((e:any)=>e.kind==='exchange'&&['learner','both'].includes(e.role)&&!['withdrawn','declined'].includes(e.status)).map((e:any)=><option key={e.id} value={e.user_id}>{e.name} · {e.title}</option>)}</Choice><label className="check"><input type="checkbox" name="credited" value="yes"/> Create a funded task for the sharer’s contribution</label></PartnerForm>}{data.matches.map((m:any)=><Card key={m.id}><h3>{m.title}</h3><p>{m.sharer_name} ↔ {m.learner_name} · {m.status}</p>{m.task_id&&<p>Time Credit follows the linked task’s confirmed duration.</p>}</Card>)}</>}
 {current==='training'&&<><h2>Training & Skill Badges</h2>{programCards('training')}<h2>Issued badges</h2>{data.badges.map((b:any)=><Card key={b.id}><h3>{b.label}</h3><p>{b.name} · {b.revoked_at?'Revoked':b.expires_at&&b.expires_at<Date.now()/1000?'Expired':'Active'}</p>{b.expires_at&&<p>Valid until {stamp(b.expires_at)}</p>}{data.capabilities.manageTraining&&!b.revoked_at&&<PartnerForm label="Revoke badge" onSave={(v:any)=>save('badge',{...v,programId:b.program_id,userId:b.user_id,revoke:true})}><PartnerField label="Reason" name="reason"/></PartnerForm>}</Card>)}{!data.badges.length&&<Blank>No Skill Badges issued yet.</Blank>}</>}
 {current==='tasks'&&<><h2>Community Tasks</h2><p>Each participant place is a real Silver Bank task with its own reserved credit and completion confirmation.</p>{programCards('task')}{data.programs.filter((p:any)=>p.kind==='task'&&p.status==='published').map((p:any)=><details key={p.id}><summary>Cancel open places · {p.title}</summary><PartnerForm label="Cancel unstarted places" onSave={(b:any)=>save('cancel-places',{...b,programId:p.id})}><PartnerField label="Reason" name="reason"/></PartnerForm></details>)}<div className="partner-grid">{data.tasks.map((t:any)=><Card key={t.id}><h3>{t.title}</h3><span className="status">{t.status.replaceAll('_',' ')}</span><p>{t.helper_name||'Place open'} · {time(t.estimated_seconds)}</p><p>{stamp(t.requested_at)}</p>{t.problem&&<p className="error">{t.problem}</p>}{t.requester_id===me.user.id&&<Button variant="outline" onClick={()=>nav('task/'+t.id)}>Open task & conversation</Button>}{t.status==='completed'&&<p>Settled: {time(t.actual_seconds)}</p>}{data.capabilities.managePrograms&&<div className="partner-actions">{t.status==='accepted'&&!t.requester_agreed&&<Button onClick={()=>act('task-action',{taskId:t.id,action:'agree',requestedAt:t.requested_at})}>Confirm schedule</Button>}{t.status==='accepted'&&!!t.requester_agreed&&!!t.helper_agreed&&!t.requester_ready&&t.requested_at<=Date.now()/1000&&<Button onClick={()=>act('task-action',{taskId:t.id,action:'start'})}>Confirm start</Button>}{t.status==='awaiting_confirmation'&&t.finished_by===t.helper_id&&<Button onClick={()=>act('task-action',{taskId:t.id,action:'confirm'})}>Confirm {time(t.actual_seconds)}</Button>}</div>}</Card>)}</div></>}
 {current==='support'&&<><h2>Community Time Support</h2>{!data.capabilities.managePrograms?<Blank>Time Support reviews are available to owners and program managers.</Blank>:<><div className="info">Available organization funding: <b>{time(data.funding?.available||0)}</b><p>Funds use the organization owner’s existing Time Credit. A budget does not create new credit. Supported time is used first when a member pays for completed help; only the amount used is shared here. Platform administrators can record funding through the existing ledger.</p></div>{programCards('support')}<h2>Private requests</h2>{data.supports.map((s:any)=><Card key={s.id}><h3>{s.title}</h3><p>{s.name} · {time(s.amount)} · {s.status}</p><p>{s.reason}</p>{s.status==='approved'&&<p>{time(s.used)} used for help · {time(s.amount-s.used)} remaining</p>}{s.status==='pending'?<PartnerForm label="Record decision" onSave={(b:any)=>save('support',{...b,id:s.id,approve:b.decision==='approve'})}><Choice label="Decision" name="decision"><option value="approve">Allocate supported time</option><option value="decline">Decline request</option></Choice><PartnerField label="Decision reason" name="reason"/></PartnerForm>:<p>{s.review_note}</p>}</Card>)}{!data.supports.length&&<Blank>No support requests yet.</Blank>}<h3>Organization ledger</h3>{data.ledger.map((l:any)=><p key={l.id}>{stamp(l.created_at)} · {l.title} · {l.type} · {time(l.amount)}</p>)}</>}</>}
 {current==='participants'&&<><h2>Participants</h2><p>Only enrollment and tasks within your organization are shown.</p>{data.participants.map((e:any)=><Card key={e.id}><h3>{e.name}</h3><p>{e.title} · {e.role} · {e.status}</p>{e.progress&&<p>Completion submission: {e.progress}</p>}{(e.kind==='training'?data.capabilities.manageTraining:data.capabilities.managePrograms)&&<>{e.status==='submitted'&&<PartnerForm label="Review completion" onSave={(b:any)=>save('review',{...b,programId:e.program_id,userId:e.user_id})}><Choice label="Decision" name="status"><option value="completed">Confirm completion</option><option value="enrolled">Return for more preparation</option><option value="declined">Decline</option></Choice><PartnerField label="Review note" name="reason"/></PartnerForm>}{e.kind==='training'&&e.status==='completed'&&<PartnerForm label="Issue Skill Badge" onSave={(b:any)=>save('badge',{...b,programId:e.program_id,userId:e.user_id})}><PartnerField label="Completion evidence / review note" name="reason"/></PartnerForm>}</>}</Card>)}{data.tasks.filter((t:any)=>t.helper_id).map((t:any)=><Card key={t.id}><h3>{t.helper_name}</h3><p>{t.title} · {t.status.replaceAll('_',' ')}</p></Card>)}{!data.participants.length&&!data.tasks.some((t:any)=>t.helper_id)&&<Blank>Participants appear when they join your programs or tasks.</Blank>}</>}
 {current==='insights'&&<><h2>Community Impact</h2><div className="partner-stats">{[...summary,['Training completions',data.participants.filter((e:any)=>e.kind==='training'&&e.status==='completed').length],['Active Skill Badges',data.badges.filter((b:any)=>!b.revoked_at&&(!b.expires_at||b.expires_at>Date.now()/1000)).length],['Completed skill exchanges',data.matches.filter((m:any)=>m.status==='completed').length],['Supported time',time(data.supports.filter((s:any)=>s.status==='approved').reduce((n:number,s:any)=>n+s.amount,0))]].map(([label,value])=><Card key={label}><p>{label}</p><strong>{value}</strong></Card>)}</div><h3>Participation by program</h3>{data.programs.map((p:any)=><div className="partner-progress" key={p.id}><label htmlFor={'progress-'+p.id}>{p.title} · {p.enrolled} / {p.capacity}</label><progress id={'progress-'+p.id} value={p.enrolled} max={p.capacity}/></div>)}</>}
 {current==='organization'&&<><h2>Organization</h2>{data.organization.role==='owner'&&<details><summary>Manage staff permissions</summary>{data.members.filter((m:any)=>m.role!=='owner').map((m:any)=><PartnerForm key={m.user_id} label={'Update '+m.name} onSave={(b:any)=>save('staff-role',{...b,userId:m.user_id})}><Choice label={m.name+' · Role'} name="role" value={m.role}><option value="staff">Community Staff · view organization activities</option><option value="program_manager">Program Manager · programs, tasks and Time Support</option><option value="training_manager">Training Manager · training and badges</option></Choice></PartnerForm>)}</details>}{data.organization.role==='owner'&&<PartnerForm label="Save public profile" onSave={(b:any)=>save('profile',b)}><PartnerField label="Public organization name" name="publicName" value={data.organization.name}/><Text label="Mission" name="mission" value={data.organization.mission}/><PartnerField label="Website" name="website" value={data.organization.website} optional type="url"/></PartnerForm>}<VerificationCenter embedded organizationId={orgId} api={api} me={{...me,verification:{...me.verification,organizations:orgs.filter((o:any)=>o.id===orgId)}}} refresh={refresh} signOut={signOut} onClose={()=>nav('home')}/><Button variant="outline" onClick={()=>nav('profile')}>Account settings</Button><Button variant="outline" onClick={signOut}>Sign out</Button></>}
 </>}
 <Dialog open={!!editor} onOpenChange={open=>!open&&setEditor(null)}><DialogContent className="partner-dialog"><DialogHeader><DialogTitle>{editor?.id?'Edit program':'Create Program'}</DialogTitle><DialogDescription>Choose an activity for your community.</DialogDescription></DialogHeader>{editor&&data&&<ProgramEditor key={editor.id||editor.kind} value={editor} me={me} data={data} onKind={(kind:string)=>setEditor({...editor,kind})} onSave={async(b:any)=>{await save('save',{...b,id:editor.id,version:editor.version,kind:editor.kind});setEditor(null)}}/>}</DialogContent></Dialog>
 </section>;
}
function ProgramEditor({value:p,me,data,onKind,onSave}:any){return <PartnerForm label="Save program" onSave={onSave}>
 {!p.id&&<Choice label="Program type" value={p.kind} onChange={(e:any)=>onKind(e.target.value)}>{Object.entries(labels).filter(([k])=>k==='training'?data.capabilities.manageTraining:data.capabilities.managePrograms).map(([k,label])=><option key={k} value={k}>{label}</option>)}</Choice>}
 <PartnerField name="title" label="Title" value={p.title} maxLength={160}/><Text name="description" label="Description / purpose" value={p.description}/>
 <Choice label="Related task category" name="categoryId" value={p.category_id||''}><option value="">Choose category</option>{me.categories.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</Choice>
 <CommunityPicker value={p.location||me.user.location}/><div className="form-grid"><PartnerField label="Scheduled date and time" name="requestedAt" type="datetime-local" optional={p.kind!=='task'} value={p.requested_at?new Date(p.requested_at*1000-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16):''}/><PartnerField label="Duration / credit per task (minutes)" name="minutes" type="number" min={1} max={10080} value={(p.duration||3600)/60}/><PartnerField label="Participant capacity" name="capacity" type="number" min={1} max={p.kind==='task'?20:100} value={p.capacity||20}/></div>
 <Text name="requirements" label={p.kind==='support'?'Eligibility requirements':'Participation requirements'} value={p.requirements} optional={p.kind!=='support'}/><PartnerField name="skills" label="Skills / areas (separate with commas)" value={p.skills} optional/>
 {p.kind==='training'?<><Text name="materials" label="Learning materials (instructions and HTTPS links)" value={p.materials} optional/><Text name="modules" label="Modules (one per line)" value={p.modules}/><Text name="completion" label="Completion requirements" value={p.completion}/><PartnerField name="badge" label="Skill Badge name" value={p.badge}/><PartnerField label="Badge validity (days; leave blank for no expiry)" name="validDays" type="number" min={1} max={3650} value={p.valid_days||''} optional/></>:<Choice name="requiredTrainingId" label="Required training / Skill Badge" value={p.required_training_id||''}><option value="">No training required</option>{data.programs.filter((x:any)=>x.kind==='training'&&x.status==='published').map((x:any)=><option value={x.id} key={x.id}>{x.title} · {x.badge}</option>)}</Choice>}
 <Choice name="relatedProgramId" label="Related program" value={p.related_program_id||''}><option value="">None</option>{data.programs.filter((x:any)=>x.id!==p.id).map((x:any)=><option value={x.id} key={x.id}>{x.title}</option>)}</Choice>
 {p.kind==='support'&&<PartnerField name="budgetMinutes" label="Time Fund budget (minutes)" type="number" min={1} max={525600} value={(p.budget||0)/60}/>}
 </PartnerForm>}
export function MemberPrograms({api,nav,focusId,userId}:any){
 const [data,setData]=useState<any>(),[error,setError]=useState('');const load=async()=>setData(await api('programs'));useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 const save=async(action:string,b:any)=>{await api('programs/'+action,b);await load()};
 return <section className="member-programs"><h2>Community Programs</h2>{error&&<p className="error">{error}</p>}{!data?<p>Loading programs…</p>:<><div className="partner-grid">{data.programs.filter((p:any)=>!focusId||p.id===focusId).map((p:any)=>{const e=data.enrollments.find((e:any)=>e.program_id===p.id),s=data.support.find((s:any)=>s.program_id===p.id);return <Card key={p.id}><span className="category">{labels[p.kind]}</span><h3>{p.title}</h3><p><ShieldCheck size={16}/> {p.organization_name}</p><p>{p.description}</p><p>{p.location} · {stamp(p.requested_at)}</p>{p.skills&&<p>Skills: {p.skills}</p>}{p.requirements&&<p>{p.requirements}</p>}{p.kind==='training'&&<><h4>Learning materials</h4><p className="partner-pre">{p.materials}</p><h4>Modules</h4><p className="partner-pre">{p.modules}</p><h4>Completion requirements</h4><p>{p.completion}</p><p>Skill Badge: {p.badge} · Community preparation, not a professional qualification.</p></>}{p.required_training_id&&<Button variant="link" onClick={()=>nav('program/'+p.required_training_id)}>View required training</Button>}
 {p.kind==='task'?<Button onClick={()=>nav('tasks')}>Find community task places</Button>:p.kind==='support'?s?<p className="info">Your private request: {s.status} · {time(s.amount)}<br/>{s.review_note}{s.status==='approved'&&<><br/>{time(s.used)} used for help · {time(s.amount-s.used)} remaining</>}</p>:<PartnerForm label="Request supported time" onSave={(b:any)=>save('support',{...b,programId:p.id})}><PartnerField label="Minutes requested" name="minutes" type="number" min={1} max={10080}/><Text label="How you meet the eligibility requirements (private)" name="reason"/></PartnerForm>:!e?<PartnerForm label="Join program" onSave={(b:any)=>save('join',{...b,programId:p.id})}>{p.kind==='exchange'&&<Choice name="role" label="I would like to be a"><option value="sharer">Skill Sharer</option><option value="learner">Skill Learner</option><option value="both">Both</option></Choice>}</PartnerForm>:<><p className="status">{e.status}</p>{e.review_note&&<p>{e.review_note}</p>}{e.status==='enrolled'&&<PartnerForm label="Submit completion for review" onSave={(b:any)=>save('progress',{...b,programId:p.id})}><Text label="Modules / activities completed and evidence" name="progress"/></PartnerForm>}</>}
 </Card>})}</div>{!data.programs.length&&<Blank>No programs have been published yet.</Blank>}<h3>My Skill Badges</h3>{data.badges.map((b:any)=><p key={b.id}><ShieldCheck size={18}/> {b.label} · {b.revoked_at?'Revoked':b.expires_at&&b.expires_at<Date.now()/1000?'Expired':'Active'}</p>)}<h3>My skill exchanges</h3>{data.matches.map((m:any)=><Card key={m.id}><h3>{m.title}</h3><p>{m.sharer_name} ↔ {m.learner_name} · {m.status}</p>{m.task_id&&m.sharer_id===userId&&<Button onClick={()=>nav('task/'+m.task_id)}>Open credited task</Button>}{m.status==='matched'&&<PartnerForm label="Confirm exchange completed" onSave={()=>save('match-confirm',{id:m.id})}/>}</Card>)}</>}</section>
}
