'use client';
import {useState} from 'react';
import {Button} from './ui/button';
const members=[
{name:'Mei Chan',area:'Sha Tin',skills:['Cooking','Cantonese conversation'],bio:'A retired cook who enjoys sharing family recipes and helping newcomers practise everyday Cantonese.',languages:'Cantonese, Mandarin',time:'Weekday mornings',offer:'Teach a small group to prepare a simple Cantonese meal.',need:'Help organising photos on her phone.',exchange:'Mei shares an hour of cooking skills; Alex helps her organise her digital photos.'},
{name:'Alex Wong',area:'Kowloon City',skills:['Technology','Digital safety'],bio:'A university student who explains smartphones, video calls and online safety in patient, simple steps.',languages:'Cantonese, English',time:'Saturday afternoons',offer:'One-to-one smartphone basics and scam-awareness practice.',need:'Learn practical home cooking.',exchange:'Alex offers technology help and learns cooking from Mei.'},
{name:'Grace Lee',area:'Tsuen Wan',skills:['Gardening','Companionship'],bio:'A keen balcony gardener who welcomes beginners and enjoys gentle community walks.',languages:'Cantonese',time:'Tuesday and Thursday mornings',offer:'Help neighbours grow herbs and care for indoor plants.',need:'Help making bilingual plant-care cards.',exchange:'Grace teaches gardening; Aisha helps write English plant-care cards.'},
{name:'Aisha Khan',area:'Yau Tsim Mong',skills:['Languages','Tutoring'],bio:'A language enthusiast who helps adults practise English and build confidence in everyday conversations.',languages:'English, Urdu, Cantonese',time:'Sunday afternoons; remote evenings',offer:'Conversational English and reading practice.',need:'Learn to grow herbs in a small flat.',exchange:'Aisha shares language skills in exchange for Grace’s gardening guidance.'},
{name:'Raymond Ho',area:'Kwun Tong',skills:['Repairs','Crafts'],bio:'A retired maker who teaches clothing mending and simple furniture care, excluding electrical or structural work.',languages:'Cantonese, Mandarin',time:'Wednesday afternoons',offer:'Show a neighbour how to sew a button or repair a loose drawer handle.',need:'Help photographing his craft projects.',exchange:'Raymond shares mending skills; Sophie helps document his work.'},
{name:'Sophie Lau',area:'Central & Western',skills:['Photography','Creative activities'],bio:'A designer who enjoys capturing community stories and running accessible drawing sessions.',languages:'Cantonese, English',time:'Weekend mornings',offer:'Portrait photography basics and beginner sketching.',need:'Learn clothing mending and practical crafts.',exchange:'Sophie shares photography skills and learns repairs from Raymond.'},
{"name": "Daniel Cheung", "area": "Tai Po", "skills": ["Music", "Companionship"], "bio": "A retired music teacher who makes rhythm and singing sessions welcoming for beginners.", "languages": "Cantonese, English", "time": "Friday mornings", "offer": "Beginner singing and simple percussion sessions.", "need": "Help designing flyers for a neighbourhood singalong.", "exchange": "Daniel could lead a singalong while Sophie creates its event photos."},
{"name": "Priya Shah", "area": "Eastern", "skills": ["Administration", "Event planning"], "bio": "An organised volunteer who helps community groups plan welcoming, accessible events.", "languages": "English, Hindi, Cantonese", "time": "Weekday evenings; remote", "offer": "Create sign-up sheets and simple volunteer schedules.", "need": "Practise conversational Cantonese.", "exchange": "Priya could organise Mei’s cooking group and practise Cantonese with her."},
{"name": "Wai Ming Lam", "area": "Tuen Mun", "skills": ["Cycling", "Bicycle care"], "bio": "A cycling enthusiast who explains basic bicycle cleaning and pre-ride checks.", "languages": "Cantonese", "time": "Saturday mornings", "offer": "Demonstrate tyre inflation and chain cleaning.", "need": "Learn to photograph community cycling activities.", "exchange": "Wai Ming could share bicycle-care skills while Sophie teaches photography basics."},
{"name": "Helen Ng", "area": "Wan Chai", "skills": ["Sewing", "Upcycling"], "bio": "A former dressmaker who enjoys giving old clothes a useful second life.", "languages": "Cantonese, Mandarin", "time": "Monday afternoons", "offer": "Teach hand stitching and reusable fabric-bag making.", "need": "Help preparing digital workshop instructions.", "exchange": "Helen could teach Alex sewing while he helps format her illustrated instructions."},
{"name": "Marco Chan", "area": "Southern", "skills": ["Pet care", "Companionship"], "bio": "An experienced pet owner who shares everyday routines and enjoys accompanied neighbourhood walks.", "languages": "Cantonese, English", "time": "Sunday mornings", "offer": "Share basic pet-care routines and join accompanied dog walks.", "need": "Learn container gardening.", "exchange": "Marco could help Grace organise a pet-friendly walk and learn herb growing from her."},
{"name": "Linda Yip", "area": "Wong Tai Sin", "skills": ["Storytelling", "Local history"], "bio": "A lifelong neighbourhood resident who enjoys preserving memories through oral storytelling.", "languages": "Cantonese", "time": "Thursday afternoons", "offer": "Share local stories and lead a small neighbourhood history discussion.", "need": "Help recording and organising audio stories.", "exchange": "Linda could share neighbourhood history while Alex helps record her stories."},
{"name": "Ethan Wu", "area": "Sai Kung", "skills": ["Accessibility", "Technology"], "bio": "A patient digital volunteer familiar with large-text settings, captions and accessible documents.", "languages": "English, Cantonese", "time": "Tuesday evenings; remote", "offer": "Help adjust phone text size and prepare readable event handouts.", "need": "Learn beginner percussion.", "exchange": "Ethan could make Daniel’s song sheets easier to read and learn rhythm skills in return."},
{"name": "Fatima Ali", "area": "Kwai Tsing", "skills": ["Languages", "Reading"], "bio": "A community reading volunteer who enjoys sharing stories across languages and cultures.", "languages": "Urdu, English, Cantonese", "time": "Saturday afternoons", "offer": "Facilitate adult reading circles and conversational Urdu practice.", "need": "Learn clothing repairs.", "exchange": "Fatima could help Helen write bilingual workshop notes and learn mending from her."},
{"name": "Chun Ho Leung", "area": "North", "skills": ["Waste reduction", "Organisation"], "bio": "A practical organiser who helps neighbours sort reusable items and plan small swap events.", "languages": "Cantonese, Mandarin", "time": "Sunday afternoons", "offer": "Organise a book swap and explain household reuse habits.", "need": "Help making an event schedule.", "exchange": "Chun Ho could organise reuse activities while Priya helps coordinate volunteer shifts."}
];
const ngos=[
{name:'Neighbour Roots Collective',area:'Sha Tin',skills:['Gardening','Companionship'],bio:'A fictional community NGO bringing generations together through gardening and regular social activities.',languages:'Cantonese, English',time:'Weekly morning sessions',offer:'Intergenerational herb garden and walking group.',need:'Volunteer garden mentors, activity helpers and translators.',exchange:'Grace could lead a beginner herb-growing session while Aisha helps prepare bilingual materials.'},
{name:'Digital Together Centre',area:'Kowloon City',skills:['Technology','Digital safety'],bio:'A fictional NGO supporting older adults to use everyday technology with confidence.',languages:'Cantonese, Mandarin, English',time:'Saturday drop-in workshops',offer:'Phone basics, video calls and online scam-awareness workshops.',need:'Patient technology buddies and workshop facilitators.',exchange:'Alex could teach phone basics; Mei could help participants practise using a recipe-sharing group.'},
{name:'Shared Table Network',area:'Kwun Tong',skills:['Cooking','Community support'],bio:'A fictional food-focused NGO organising community kitchens and shared learning.',languages:'Cantonese, English',time:'Weekday cooking groups',offer:'Budget-friendly cooking demonstrations and community meal preparation.',need:'Cooking mentors, event helpers and bilingual recipe writers.',exchange:'Mei could demonstrate a recipe and Sophie could photograph the steps for a community booklet.'},
{name:'Bridge Generations Hub',area:'Yau Tsim Mong',skills:['Languages','Crafts','Creative activities'],bio:'A fictional NGO connecting people through language exchange, storytelling and creative workshops.',languages:'Cantonese, English, Urdu',time:'Weekend workshops',offer:'Language circles, repair cafés and community storytelling.',need:'Language buddies, craft mentors and photographers.',exchange:'Raymond could lead a mending workshop while Sophie records participants’ community stories.'},
{"name": "Neighbour Notes Society", "area": "Tai Po", "skills": ["Music", "Companionship"], "bio": "A fictional NGO using music and shared storytelling to strengthen social connections.", "languages": "Cantonese, English", "time": "Friday morning groups", "offer": "Beginner community choir and rhythm circles.", "need": "Music mentors, accessible song-sheet designers and session helpers.", "exchange": "Daniel could lead singing while Ethan prepares large-print song sheets."},
{"name": "Second Stitch Community", "area": "Wan Chai", "skills": ["Sewing", "Upcycling"], "bio": "A fictional NGO helping residents share repair skills and reduce textile waste.", "languages": "Cantonese, Mandarin, English", "time": "Monday afternoon workshops", "offer": "Clothing-mending circles and reusable-bag workshops.", "need": "Sewing mentors, translators and material organisers.", "exchange": "Helen and Raymond could teach repairs while Fatima helps with bilingual instructions."},
{"name": "Open Pages Circle", "area": "Kwai Tsing", "skills": ["Reading", "Languages"], "bio": "A fictional NGO offering welcoming reading and language activities for adults.", "languages": "English, Cantonese, Urdu", "time": "Weekend reading circles", "offer": "Multilingual storytelling and conversational reading groups.", "need": "Reading buddies, language facilitators and book-swap helpers.", "exchange": "Fatima and Aisha could run a language circle while Chun Ho organises a book exchange."},
{"name": "Access Everyday Alliance", "area": "Sai Kung", "skills": ["Accessibility", "Technology"], "bio": "A fictional NGO making everyday community information easier to read and use.", "languages": "Cantonese, English", "time": "Remote weekday support; monthly workshops", "offer": "Accessible phone settings and large-print community guides.", "need": "Digital volunteers, document designers and patient peer mentors.", "exchange": "Ethan and Alex could demonstrate accessible phone settings; Sophie could help lay out handouts."},
{"name": "Green Routes Neighbours", "area": "Tuen Mun", "skills": ["Cycling", "Waste reduction"], "bio": "A fictional NGO encouraging shared repair knowledge and environmentally mindful neighbourhood activities.", "languages": "Cantonese, Mandarin", "time": "Saturday morning sessions", "offer": "Basic bicycle-care demonstrations and community reuse events.", "need": "Bicycle-care mentors, event organisers and reuse volunteers.", "exchange": "Wai Ming could demonstrate bicycle cleaning while Chun Ho organises a reusable-items swap."},
{"name": "Local Stories & Paws Hub", "area": "Southern", "skills": ["Local history", "Pet care", "Companionship"], "bio": "A fictional NGO bringing neighbours together through local stories and accompanied pet-friendly activities.", "languages": "Cantonese, English", "time": "Sunday morning gatherings", "offer": "Neighbourhood story circles and accompanied pet-friendly walks.", "need": "Storytellers, experienced pet owners and volunteer photographers.", "exchange": "Linda could share neighbourhood memories, Marco could help with pet-friendly activities and Sophie could record the event."}
];
export function SampleCommunity(){
const [kind,setKind]=useState('all'),[query,setQuery]=useState('');
const all=[...members.map(p=>({...p,type:'Member'})),...ngos.map(p=>({...p,type:'NGO'}))];
const results=all.filter(p=>(kind==='all'||kind===p.type)&&[p.name,p.area,p.bio,...p.skills,p.languages].join(' ').toLowerCase().includes(query.trim().toLowerCase()));
return <section className="sample-community"><p>Explore {members.length} sample members and {ngos.length} sample NGOs. All names and profiles below are fictional examples. They cannot receive messages, accept tasks or exchange Time Credit.</p><div className="sample-controls"><label>Search skills, name or district<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try gardening or technology" type="search"/></label><label>Profile type<select value={kind} onChange={e=>setKind(e.target.value)}><option value="all">Members and NGOs</option><option value="Member">Members</option><option value="NGO">NGOs</option></select></label></div><p role="status">{results.length} sample profiles</p><div className="sample-grid">{results.map(p=><article className="sample-profile" key={p.name}><div className="sample-profile-heading"><span className="avatar" aria-hidden="true">{p.name.split(' ').slice(0,2).map(n=>n[0]).join('')}</span><div><small>Sample {p.type} · Fictional</small><h2>{p.name}</h2><p>{p.area}</p></div></div><p>{p.bio}</p><ul className="sample-skills" aria-label="Strengths">{p.skills.map(s=><li key={s}>{s}</li>)}</ul><dl><dt>{p.type==='NGO'?'Programs':'Can offer'}</dt><dd>{p.offer}</dd><dt>{p.type==='NGO'?'Volunteer strengths needed':'Would welcome'}</dt><dd>{p.need}</dd><dt>Languages</dt><dd>{p.languages}</dd><dt>Sample availability</dt><dd>{p.time}</dd></dl><details><summary>See an example match</summary><p>{p.exchange}</p><small>Illustrative match only; no booking or credit transfer takes place.</small></details></article>)}</div>{results.length===0&&<div className="sample-profile"><p>No sample profiles match your search.</p><Button variant="outline" onClick={()=>{setQuery('');setKind('all')}}>Clear filters</Button></div>}</section>
}
