'use client';
import {useState} from 'react';
import {Button} from './ui/button';
const members=[
{name:'Mei Chan',area:'Sha Tin',skills:['Cooking','Cantonese conversation'],bio:'A retired cook who enjoys sharing family recipes and helping newcomers practise everyday Cantonese.',languages:'Cantonese, Mandarin',time:'Weekday mornings',offer:'Teach a small group to prepare a simple Cantonese meal.',need:'Help organising photos on her phone.',exchange:'Mei shares an hour of cooking skills; Alex helps her organise her digital photos.'},
{name:'Alex Wong',area:'Kowloon City',skills:['Technology','Digital safety'],bio:'A university student who explains smartphones, video calls and online safety in patient, simple steps.',languages:'Cantonese, English',time:'Saturday afternoons',offer:'One-to-one smartphone basics and scam-awareness practice.',need:'Learn practical home cooking.',exchange:'Alex offers technology help and learns cooking from Mei.'},
{name:'Grace Lee',area:'Tsuen Wan',skills:['Gardening','Companionship'],bio:'A keen balcony gardener who welcomes beginners and enjoys gentle community walks.',languages:'Cantonese',time:'Tuesday and Thursday mornings',offer:'Help neighbours grow herbs and care for indoor plants.',need:'Help making bilingual plant-care cards.',exchange:'Grace teaches gardening; Aisha helps write English plant-care cards.'},
{name:'Aisha Khan',area:'Yau Tsim Mong',skills:['Languages','Tutoring'],bio:'A language enthusiast who helps adults practise English and build confidence in everyday conversations.',languages:'English, Urdu, Cantonese',time:'Sunday afternoons; remote evenings',offer:'Conversational English and reading practice.',need:'Learn to grow herbs in a small flat.',exchange:'Aisha shares language skills in exchange for Grace’s gardening guidance.'},
{name:'Raymond Ho',area:'Kwun Tong',skills:['Repairs','Crafts'],bio:'A retired maker who teaches clothing mending and simple furniture care, excluding electrical or structural work.',languages:'Cantonese, Mandarin',time:'Wednesday afternoons',offer:'Show a neighbour how to sew a button or repair a loose drawer handle.',need:'Help photographing his craft projects.',exchange:'Raymond shares mending skills; Sophie helps document his work.'},
{name:'Sophie Lau',area:'Central & Western',skills:['Photography','Creative activities'],bio:'A designer who enjoys capturing community stories and running accessible drawing sessions.',languages:'Cantonese, English',time:'Weekend mornings',offer:'Portrait photography basics and beginner sketching.',need:'Learn clothing mending and practical crafts.',exchange:'Sophie shares photography skills and learns repairs from Raymond.'}
];
const ngos=[
{name:'Neighbour Roots Collective',area:'Sha Tin',skills:['Gardening','Companionship'],bio:'A fictional community NGO bringing generations together through gardening and regular social activities.',languages:'Cantonese, English',time:'Weekly morning sessions',offer:'Intergenerational herb garden and walking group.',need:'Volunteer garden mentors, activity helpers and translators.',exchange:'Grace could lead a beginner herb-growing session while Aisha helps prepare bilingual materials.'},
{name:'Digital Together Centre',area:'Kowloon City',skills:['Technology','Digital safety'],bio:'A fictional NGO supporting older adults to use everyday technology with confidence.',languages:'Cantonese, Mandarin, English',time:'Saturday drop-in workshops',offer:'Phone basics, video calls and online scam-awareness workshops.',need:'Patient technology buddies and workshop facilitators.',exchange:'Alex could teach phone basics; Mei could help participants practise using a recipe-sharing group.'},
{name:'Shared Table Network',area:'Kwun Tong',skills:['Cooking','Community support'],bio:'A fictional food-focused NGO organising community kitchens and shared learning.',languages:'Cantonese, English',time:'Weekday cooking groups',offer:'Budget-friendly cooking demonstrations and community meal preparation.',need:'Cooking mentors, event helpers and bilingual recipe writers.',exchange:'Mei could demonstrate a recipe and Sophie could photograph the steps for a community booklet.'},
{name:'Bridge Generations Hub',area:'Yau Tsim Mong',skills:['Languages','Crafts','Creative activities'],bio:'A fictional NGO connecting people through language exchange, storytelling and creative workshops.',languages:'Cantonese, English, Urdu',time:'Weekend workshops',offer:'Language circles, repair cafés and community storytelling.',need:'Language buddies, craft mentors and photographers.',exchange:'Raymond could lead a mending workshop while Sophie records participants’ community stories.'}
];
export function SampleCommunity(){
const [kind,setKind]=useState('all'),[query,setQuery]=useState('');
const all=[...members.map(p=>({...p,type:'Member'})),...ngos.map(p=>({...p,type:'NGO'}))];
const results=all.filter(p=>(kind==='all'||kind===p.type)&&[p.name,p.area,p.bio,...p.skills,p.languages].join(' ').toLowerCase().includes(query.trim().toLowerCase()));
return <section className="sample-community"><p>Explore six sample members and four sample NGOs. All names and profiles below are fictional examples. They cannot receive messages, accept tasks or exchange Time Credit.</p><div className="sample-controls"><label>Search skills, name or district<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try gardening or technology" type="search"/></label><label>Profile type<select value={kind} onChange={e=>setKind(e.target.value)}><option value="all">Members and NGOs</option><option value="Member">Members</option><option value="NGO">NGOs</option></select></label></div><p role="status">{results.length} sample profiles</p><div className="sample-grid">{results.map(p=><article className="sample-profile" key={p.name}><div className="sample-profile-heading"><span className="avatar" aria-hidden="true">{p.name.split(' ').slice(0,2).map(n=>n[0]).join('')}</span><div><small>Sample {p.type} · Fictional</small><h2>{p.name}</h2><p>{p.area}</p></div></div><p>{p.bio}</p><ul className="sample-skills" aria-label="Strengths">{p.skills.map(s=><li key={s}>{s}</li>)}</ul><dl><dt>{p.type==='NGO'?'Programs':'Can offer'}</dt><dd>{p.offer}</dd><dt>{p.type==='NGO'?'Volunteer strengths needed':'Would welcome'}</dt><dd>{p.need}</dd><dt>Languages</dt><dd>{p.languages}</dd><dt>Sample availability</dt><dd>{p.time}</dd></dl><details><summary>See an example match</summary><p>{p.exchange}</p><small>Illustrative match only; no booking or credit transfer takes place.</small></details></article>)}</div>{results.length===0&&<div className="sample-profile"><p>No sample profiles match your search.</p><Button variant="outline" onClick={()=>{setQuery('');setKind('all')}}>Clear filters</Button></div>}</section>
}
