'use client';
import React,{useRef,useState} from 'react';
import {Button} from './ui/button';
import {tr,getLanguage} from '@/lib/i18n';
type Point=[number,number];
export function SignaturePad(){
 const [strokes,setStrokes]=useState<Point[][]>([]);const drawing=useRef(false);const svg=useRef<SVGSVGElement>(null);
 const point=(e:React.PointerEvent)=>{const r=svg.current!.getBoundingClientRect();return [Math.max(0,Math.min(1000,(e.clientX-r.left)/r.width*1000)),Math.max(0,Math.min(300,(e.clientY-r.top)/r.height*300))].map(Math.round) as Point;};
 const cursor=useRef<Point>([500,150]);const keyboard=useRef(false);
 const stop=()=>{drawing.current=false;};
 return <div className="signature-pad"><p>{tr('Sign in the box using your finger, mouse or pen.')}</p><svg ref={svg} viewBox="0 0 1000 300" preserveAspectRatio="none" role="application" tabIndex={0} aria-label={tr('Handwritten signature')} aria-describedby="signature-keyboard-help" onKeyDown={e=>{if(e.key===' '){e.preventDefault();keyboard.current=!keyboard.current;if(keyboard.current)setStrokes(s=>s.length<100?[...s,[cursor.current]]:s);return;}const offsets:Record<string,Point>={ArrowLeft:[-10,0],ArrowRight:[10,0],ArrowUp:[0,-10],ArrowDown:[0,10]};if(offsets[e.key]){e.preventDefault();const d=offsets[e.key];cursor.current=[Math.max(0,Math.min(1000,cursor.current[0]+d[0])),Math.max(0,Math.min(300,cursor.current[1]+d[1]))];if(keyboard.current)setStrokes(s=>s.length&&s.reduce((n,x)=>n+x.length,0)<3000?[...s.slice(0,-1),[...s[s.length-1],cursor.current]]:s)}}} onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);drawing.current=true;setStrokes(s=>s.length<100?[...s,[point(e)]]:s)}} onPointerMove={e=>{if(!drawing.current)return;const p=point(e);setStrokes(s=>{if(!s.length||s.reduce((n,x)=>n+x.length,0)>=3000)return s;return [...s.slice(0,-1),[...s[s.length-1],p]]})}} onPointerUp={stop} onPointerCancel={stop}>{strokes.map((s,i)=><polyline key={i} points={s.map(p=>p.join(',')).join(' ')} fill="none" stroke="currentColor" strokeWidth="5" strokeLinecap="round" strokeLinejoin="round"/>)}</svg><small id="signature-keyboard-help">{tr('Keyboard: focus the box, press Space to start a stroke, use arrow keys, then press Space to finish.')}</small><input type="hidden" name="signatureDrawing" value={strokes.length?JSON.stringify(strokes):''}/><Button variant="outline" type="button" onClick={()=>{setStrokes([]);keyboard.current=false;drawing.current=false}}>{tr('Clear signature')}</Button><span role="status">{tr(strokes.some(s=>s.length>1)?'Signature added':'Signature required')}</span></div>
}
export function SavedAgreements({agreements}:any){return <details className="saved-agreements"><summary>{tr('Your signed agreements')}</summary>{agreements.map((a:any,i:number)=><div className="review" key={i}><b>{tr(a.kind==='community'?'Community agreements':'Private interaction agreement')}</b><p>{a.signature} · {new Date(a.accepted_at*1000).toLocaleString(getLanguage())}</p>{a.signature_drawing&&<svg viewBox="0 0 1000 300" role="img" aria-label={tr('Saved handwritten signature')}>{(JSON.parse(a.signature_drawing) as Point[][]).map((s,j)=><polyline key={j} points={s.map(p=>p.join(',')).join(' ')} stroke="currentColor" strokeWidth="5" fill="none" strokeLinecap="round"/>)}</svg>}<small>{tr('Version')}: {a.version.slice(0,12)}</small></div>)}</details>}
