'use client';
import React,{useRef,useState,useEffect} from 'react';
import {motion,MotionConfig,useScroll,useTransform,useReducedMotion,useInView,MotionValue} from 'motion/react';
import {ArrowUpRight,ArrowRight,Clock,Heart,HeartHandshake,BookOpen,Users,ShieldCheck,Activity,MessageCircle,Building2,Check,Menu,X,LockKeyhole,Leaf} from 'lucide-react';
import {BankSolutions,CareSolutions} from './silver-solutions';
import {Hero} from './ui/animated-hero';
import {Button} from './ui/button';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from './ui/accordion';
export function SilverBrand({bank=false,iconOnly=false}:{bank?:boolean;iconOnly?:boolean}){return <span className="silver-brand-lockup"><img src={bank?"/images/brand/silver-bank.jpeg":"/images/brand/silver-plus.jpeg"} alt={iconOnly?'Silver Bank':''}/>{!iconOnly&&<span className="silver-plus-brand">Silver<sup>+</sup>{bank&&<small>Silver Bank</small>}</span>}</span>}
function Reveal({children,className='',paused=false,index=0,as='div'}:{children:React.ReactNode;className?:string;paused?:boolean;index?:number;as?:'div'|'article'|'li'}){const reduced=useReducedMotion();const ref=useRef<HTMLElement|null>(null);const inView=useInView(ref,{once:true,amount:.2});const Tag=as==='article'?motion.article:as==='li'?motion.li:motion.div;return <Tag ref={(node:HTMLElement|null)=>{ref.current=node}} className={className} initial={false} animate={paused||reduced?{opacity:1,y:0,scale:1}:{opacity:inView?1:.4,y:inView?0:28,scale:inView?1:.98}} whileHover={paused||reduced?{}:{y:-4}} transition={{duration:.65,delay:inView?index*.1:0,ease:[.22,1,.36,1]}}>{children}</Tag>}
function Word({word,index,total,progress,plain}:{word:string;index:number;total:number;progress:MotionValue<number>;plain:boolean}){const opacity=useTransform(progress,[index/total,(index+1)/total],[.25,1]);return <motion.span style={{opacity:plain?1:opacity}}>{word} </motion.span>}
function ScrollWords({paused}:{paused:boolean}){const ref=useRef<HTMLParagraphElement>(null);const {scrollYProgress}=useScroll({target:ref,offset:['start .95','end .85']});const reduced=useReducedMotion();const text='Feel well. Stay connected. Silver⁺ brings everyday wellbeing and community participation together.';return <p ref={ref} className="sp-scroll-words" aria-label={text}><span aria-hidden="true">{text.split(' ').map((word,i,words)=><Word key={i} word={word} index={i} total={words.length} progress={scrollYProgress} plain={!!reduced||paused}/>)}</span></p>}
function ScrollHeading({children,paused=false,id}:{children:React.ReactNode;paused?:boolean;id?:string}){
 const ref=useRef<HTMLHeadingElement>(null);const {scrollYProgress}=useScroll({target:ref,offset:['start .95','end .85']});const reduced=useReducedMotion();
 const textOf=(nodes:React.ReactNode):string=>React.Children.toArray(nodes).map(n=>typeof n==='string'||typeof n==='number'?String(n):React.isValidElement(n)?n.type==='br'?' ':textOf((n.props as any).children):'').join('');
 const text=textOf(children);const total=text.trim().split(/\s+/).length;let index=0;
 const render=(nodes:React.ReactNode):React.ReactNode=>React.Children.map(nodes,n=>{if(typeof n==='string'||typeof n==='number')return String(n).split(/(\s+)/).map((word,i)=>word.trim()?<Word key={i} word={word} index={index++} total={total} progress={scrollYProgress} plain={!!reduced||paused}/>:null);if(React.isValidElement(n)){if(n.type==='br')return n;return React.cloneElement(n as React.ReactElement<any>,{},render((n.props as any).children))}return n});
 return <h2 ref={ref} id={id} className="sp-reveal-heading" aria-label={text}><span aria-hidden="true">{render(children)}</span></h2>;
}

// Pin a chapter only after its entire content has scrolled into view. The next
// opaque chapter then rises over it, without trapping native scrolling.
function Chapter({children,className='',...props}:React.ComponentProps<'section'>){
 const ref=useRef<HTMLElement>(null);const reduced=useReducedMotion();const [top,setTop]=useState<number>();
 useEffect(()=>{const el=ref.current;if(!el)return;const measure=()=>setTop(Math.min(96,window.innerHeight-el.offsetHeight));const observer=new ResizeObserver(measure);observer.observe(el);window.addEventListener('resize',measure);measure();return()=>{observer.disconnect();window.removeEventListener('resize',measure)}},[]);
 return <><div className="sp-chapter-anchor" aria-hidden="true"/><section {...props} ref={ref} className={'sp-chapter '+className} style={{...props.style,position:reduced?'relative':undefined,top:reduced?undefined:top}}>{children}</section></>;
}
const questions=[
 ['What is Silver⁺?', 'Silver⁺ brings together Silver Care’s health-support vision and Silver Bank’s exchange of time, skills and everyday help, helping older adults stay active, connected and independent.'],
 ['What is the difference between an ordinary healthcare app and Silver Care?', 'Silver Care organizes symptoms, check-ins and supported device information for clearer conversations with doctors. With permission, it could also help Silver Bank suggest suitable activities. It does not diagnose conditions or replace doctors.'],
 ['Why does Silver Bank use time instead of money?', 'Everyone’s time has equal value. Help someone to earn Time Credit, then use it to receive help, valuing people’s skills and experience regardless of age, profession or task.'],
 ['What happens if I do not have enough Time Credit?', 'You may receive Community Time Support through approved NGO or Community Partner programs and community funds, helping people who temporarily struggle to earn enough credit. Support depends on program approval and available funds.'],
 ['Does AI make final decisions about users, disputes, or fraud?', 'No. AI may assist with matching, summaries and unusual-activity checks. Authorized people review important decisions about disputes, fraud and account suspensions.']
];

const benefits=[{icon:Users,title:'Stay connected',text:'Make everyday moments more meaningful with people nearby.'},{icon:BookOpen,title:'Share what you know',text:'Pass on your skills, experience and stories.'},{icon:HeartHandshake,title:'Give and receive',text:'Offer a helping hand. Ask for one when you need it.'},{icon:Leaf,title:'Keep your independence',text:'Find ways to participate that fit your own pace.'}];
export function SilverLanding({onStart,onSignIn,onEnter,onCare,signedIn=false}:{onStart:()=>void;onSignIn:()=>void;onEnter:()=>void;onCare:()=>void;signedIn?:boolean}){
 const [menu,setMenu]=useState(false);const paused=false;const reduced=useReducedMotion();const scroll=(id:string)=>{setMenu(false);const target=document.getElementById(id);if(!target)return;const chapter=target.closest('.sp-chapter');const anchor=chapter?.previousElementSibling;const top=anchor?anchor.getBoundingClientRect().top+window.scrollY+(target===chapter?0:target.getBoundingClientRect().top-chapter!.getBoundingClientRect().top)-110:target.getBoundingClientRect().top+window.scrollY-110;window.scrollTo({top,behavior:paused||reduced?'auto':'smooth'})};
 return <MotionConfig reducedMotion={paused?'always':'user'}><div className={'silver-landing'+(paused?' sp-paused':'')}><a className="sp-skip" href="#sp-main">Skip to content</a><header className="sp-nav"><button className="sp-logo" aria-label="Silver⁺ introduction" onClick={()=>scroll('sp-top')}><SilverBrand/></button><nav className={menu?'sp-nav-links is-open':'sp-nav-links'} aria-label="Introduction navigation">{[['About','sp-about'],['Silver Bank','sp-bank'],['Silver Care','sp-care'],['How it works','sp-how'],['Community','sp-community']].map(([label,id])=><button key={id} onClick={()=>scroll(id)}>{label}</button>)}</nav><div className="sp-nav-actions"><button className="sp-signin" onClick={signedIn?onEnter:onSignIn}>{signedIn?'Open app':'Sign In'}</button><Button className="sp-nav-cta" onClick={signedIn?onEnter:onStart}>{signedIn?'Silver Bank':'Get Started'}<ArrowUpRight size={17}/></Button><button className="sp-menu" aria-expanded={menu} aria-label={menu?'Close navigation':'Open navigation'} onClick={()=>setMenu(v=>!v)}>{menu?<X/>:<Menu/>}</button></div></header>
 <main id="sp-main"><div id="sp-top"><Hero onStart={signedIn?onEnter:onStart} onExplore={()=>scroll('sp-about')} paused={paused}/></div>
 <Chapter className="sp-section sp-about" id="sp-about"><p className="sp-eyebrow">About Silver⁺</p><ScrollWords paused={paused}/><div className="sp-two-copy"><p>Silver Bank connects people through an equal exchange of time, skills and everyday help.</p><p>Silver Care brings wellbeing conversations, personal records and family contacts into one private space.</p></div></Chapter>
 <Chapter className="sp-section sp-products" aria-labelledby="sp-ecosystem"><div className="sp-section-heading"><p className="sp-eyebrow">02 / One connected ecosystem</p><ScrollHeading paused={paused} id="sp-ecosystem">Your wellbeing.<br/>Your place in the community.</ScrollHeading></div>
 <Reveal className="sp-product sp-bank" paused={paused}><div id="sp-bank" className="sp-product-copy"><span className="sp-product-label"><img className="sp-bank-logo" src="/images/brand/silver-bank.jpeg" alt="Silver Bank logo"/> Silver Bank</span><h3>Give an hour.<br/>Receive a little more<br/>from life.</h3><p>Give time. Earn Time Credit. Receive help when you need it.</p><ul><li><Check/>Request help or lend a hand</li><li><Check/>Share skills and join community activities</li><li><Check/>Everyone can give and receive</li></ul><Button onClick={()=>scroll('sp-bank-details')}>Explore Silver Bank <ArrowUpRight size={18}/></Button></div><div className="sp-bank-visual" aria-label="An example of a one-hour time exchange"><div className="sp-example-label">A simple exchange</div><div className="sp-hour"><Clock/><strong>1 hour</strong><span>given = 1 hour received</span></div><div className="sp-exchange-row"><span><BookOpen/> Share a skill</span><ArrowRight/><span><HeartHandshake/> Get support</span></div><p>Experience has value.<br/>At every age.</p></div></Reveal>
 <Reveal className="sp-product sp-care" paused={paused}><div id="sp-care" className="sp-product-copy"><span className="sp-product-label"><img className="sp-bank-logo" src="/images/brand/silver-care.png" alt="Silver Care logo"/> Silver Care</span><h3>A clearer picture<br/>of how you feel.</h3><p>Bring your symptom notes, wellbeing check-ins and supported device information into one private place. Prepare an editable summary for your next appointment.</p><ul><li><Check/>Health and activity information</li><li><Check/>Symptoms, timing and changes</li><li><Check/>Clearer conversations about wellbeing</li></ul><p className="sp-small">Health-information support, not diagnosis or a replacement for a doctor.</p><Button onClick={()=>scroll('sp-care-details')}>Explore Silver Care <ArrowUpRight size={18}/></Button></div><div className="sp-care-visual"><div className="sp-care-preview"><span className="sp-example-label">Silver Care · Your private wellbeing space</span><h4>How are you<br/>feeling today?</h4><div className="sp-wellbeing-row"><Heart/><span>Health information<small>Supported wearable indicators</small></span></div><div className="sp-wellbeing-row"><MessageCircle/><span>Your own words<small>Record what changed and when</small></span></div><div className="sp-wellbeing-row"><Activity/><span>Your daily rhythm<small>Activity and movement patterns</small></span></div><div className="sp-care-note"><LockKeyhole size={16}/> Sharing stays your choice</div></div></div></Reveal></Chapter>
 <Chapter className="sp-section sp-product-story" id="sp-bank-details">
 <div className="sp-story-title"><span className="sp-product-label"><HeartHandshake/> Silver Bank</span><ScrollHeading paused={paused}>Everyone has something to give.</ScrollHeading></div>
 <div className="sp-story-problem"><h3>The problem</h3><p>Experience can go unused while everyday help stays out of reach. Different generations need more ways to connect.</p></div>
 <div className="sp-story-solution" id="sp-how"><h3>The solution</h3><p>Exchange help through Time Credit. One hour given has the same value as one hour received.</p><BankSolutions/></div>
 <div className="sp-story-innovation"><h3>What makes it different</h3><div><article><BookOpen/><h4>Experience has equal value</h4><p>Time connects people across ages and backgrounds.</p></article><article><Building2/><h4>Community support</h4><p>Approved partners offer training, Skill Badges and Time Support programs.</p></article></div><p className="sp-story-safeguard">Verified people and organizations. Human review for disputes and important decisions.</p></div>
 <Button onClick={signedIn?onEnter:onStart}>Get started with Silver Bank <ArrowUpRight size={18}/></Button>
 </Chapter>
 <Chapter className="sp-section sp-product-story sp-care-story" id="sp-care-details">
 <div className="sp-story-title"><span className="sp-product-label"><Heart/> Silver Care</span><ScrollHeading paused={paused}>Your wellbeing, in your own words.</ScrollHeading></div>
 <div className="sp-story-problem"><h3>The problem</h3><p>Small changes are easy to forget. Scattered notes can make it harder to explain how you feel or prepare for an appointment.</p></div>
 <div className="sp-care-solution"><div><h3>The solution</h3><p>Talk or type naturally. Keep physical concerns in My Health and your family within reach.</p></div><CareSolutions/></div>
 <div className="sp-story-innovation"><h3>What makes it different</h3><p>Physical health notes, personal observations and compatible watch readings come together, with sharing under your control.</p><p>Choose broad activity preferences for Silver Bank without sharing symptoms or raw health records.</p><p className="sp-story-safeguard">AI supports reflection, not diagnosis. Watch readings require a compatible connection.</p></div>
 <Button onClick={onCare}>Get started with Silver Care <ArrowUpRight size={18}/></Button>
 </Chapter>
 <Chapter className="sp-section sp-community" id="sp-community"><div><ScrollHeading paused={paused}>A community for every generation.</ScrollHeading><p className="sp-intro">Give support. Find support. Stay involved in a way that suits you.</p></div><div className="sp-audiences">{[['Older adults','Share experience, keep connections and receive everyday help.'],['Younger people','Offer practical skills and learn from another generation.'],['Community Partners','Create trusted programs, learning opportunities and local support.'],['Families','Keep loved ones within reach. Health sharing remains their choice.']].map(([title,text])=><article key={title}><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></Chapter>
 <Chapter className="sp-section sp-faq" id="sp-faq" aria-labelledby="sp-faq-heading"><div><p className="sp-eyebrow">Questions & answers</p><ScrollHeading paused={paused} id="sp-faq-heading">A little more clarity.</ScrollHeading></div><Accordion type="single" collapsible className="sp-faq-list">{questions.map(([question,answer],i)=><AccordionItem value={'question-'+i} key={question}><AccordionTrigger>{question}</AccordionTrigger><AccordionContent><p>{answer}</p></AccordionContent></AccordionItem>)}</Accordion></Chapter>
 <Chapter className="sp-section sp-final"><p className="sp-eyebrow">Your next chapter is a shared one.</p><ScrollHeading paused={paused}>More connection.<br/>More possibility.<br/><span>More you.</span></ScrollHeading><Button onClick={signedIn?onEnter:onStart}>Get started with Silver Bank <ArrowUpRight/></Button><Button onClick={onCare}>Get started with Silver Care <ArrowUpRight/></Button>{!signedIn&&<button className="sp-bottom-signin" onClick={onSignIn}>Already have an account? Sign In</button>}</Chapter>
 </main><footer className="sp-footer"><SilverBrand/><p>Wellbeing. Community. Together.</p><div><button onClick={()=>scroll('sp-bank')}>Silver Bank</button><button onClick={()=>scroll('sp-care')}>Silver Care</button><button onClick={()=>scroll('sp-about')}>About</button><button onClick={()=>scroll('sp-faq')}>Q&A</button><a href="/guidelines/silver-care-guidelines.pdf" target="_blank" rel="noreferrer">Community guidelines</a></div><small>© {new Date().getFullYear()} Silver⁺</small></footer></div></MotionConfig>
}
