'use client';
import React,{useEffect,useRef,useState} from 'react';
import {Button} from './ui/button';
import {Input} from './ui/input';
import {Textarea} from './ui/textarea';
import {tr,getLanguage} from '@/lib/i18n';
async function preparePhoto(file:File){
 if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Choose a JPEG, PNG or WebP photo.');
 if(file.size>20000000)throw new Error('Photo is too large. Choose a smaller photo.');
 const url=URL.createObjectURL(file);try{const image=new Image();image.src=url;await image.decode();const scale=Math.min(1,1600/Math.max(image.naturalWidth,image.naturalHeight));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));const ctx=canvas.getContext('2d')!;ctx.fillStyle='white';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(image,0,0,canvas.width,canvas.height);let quality=.85,data=canvas.toDataURL('image/jpeg',quality);while(data.length>800000&&quality>.25){quality-=.1;data=canvas.toDataURL('image/jpeg',quality)}if(data.length>800000)throw new Error('Photo is too large. Choose a smaller photo.');return data;}finally{URL.revokeObjectURL(url)}
}
export function TaskConversation({taskId,userId,messages,api}:any){
 const [items,setItems]=useState<any[]>(messages),[content,setContent]=useState(''),[photo,setPhoto]=useState(''),[error,setError]=useState(''),[pending,setPending]=useState(false),[preparing,setPreparing]=useState(false),[more,setMore]=useState(messages.length===10),[view,setView]=useState('');const fileInput=useRef<HTMLInputElement>(null);const dialog=useRef<HTMLDialogElement>(null);
 const merge=(incoming:any[])=>setItems(old=>[...new Map([...old,...incoming].map(m=>[m.id,m])).values()].sort((a,b)=>a.cursor-b.cursor));
 useEffect(()=>{if(items.length&&messages.length===10&&messages[0].cursor>items[items.length-1].cursor){setItems(messages);setMore(true)}else merge(messages)},[messages]);useEffect(()=>{if(view)dialog.current?.showModal();else dialog.current?.close()},[view]);
 return <>{more&&<Button type="button" variant="outline" disabled={pending} onClick={async()=>{setPending(true);try{const older=await api(`tasks/${taskId}/messages?before=${items[0]?.cursor}`);merge(older);setMore(older.length===10)}catch(e:any){setError(e.message)}finally{setPending(false)}}}>{tr('Load older messages')}</Button>}<div className="messages">{items.length?items.map(m=><div key={m.id} className={'message '+(m.sender_id===userId?'mine':'')}><strong>{m.sender_name}</strong>{m.content&&<p>{m.content}</p>}{m.photo&&<button type="button" className="chat-photo-button" onClick={()=>setView(m.photo)} aria-label={tr('Open photo')}><img className="chat-photo" src={m.photo} alt={tr('Photo shared in this task')} loading="lazy"/></button>}<small>{new Date(m.created_at*1000).toLocaleString(getLanguage())}</small></div>):<p>{tr('Your private conversation starts here.')}</p>}</div><form onSubmit={async e=>{e.preventDefault();setPending(true);setError('');try{await api(`tasks/${taskId}/message`,{content,photo});setContent('');setPhoto('');if(fileInput.current)fileInput.current.value='';merge(await api(`tasks/${taskId}/messages`))}catch(e:any){setError(e.message)}finally{setPending(false)}}}><fieldset disabled={pending||preparing}><label className="field"><span>{tr('Your message')}</span><Textarea value={content} onChange={e=>setContent(e.target.value)} maxLength={4000}/></label><label className="field"><span>{tr('Add a photo')}</span><Input ref={fileInput} type="file" accept="image/jpeg,image/png,image/webp" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setPreparing(true);setError('');setPhoto('');try{setPhoto(await preparePhoto(file))}catch(err:any){setError(err.message)}finally{setPreparing(false)}}}/></label>{photo&&<div className="photo-preview"><img className="chat-photo" src={photo} alt={tr('Photo preview')}/><Button type="button" variant="outline" onClick={()=>{setPhoto('');if(fileInput.current)fileInput.current.value=''}}>{tr('Remove photo')}</Button></div>}<p className="hint">{tr('Photos are shared only with the other task participant. You can send a photo with or without a message.')}</p>{error&&<p className="error" role="alert">{tr(error)}</p>}<Button type="submit" disabled={!content.trim()&&!photo}>{tr(preparing?'Preparing photo…':pending?'Sending…':'Send message')}</Button></fieldset></form><dialog ref={dialog} className="photo-dialog" onCancel={()=>setView('')}><Button type="button" variant="outline" onClick={()=>setView('')}>{tr('Close photo')}</Button>{view&&<img src={view} alt={tr('Photo shared in this task')}/>}</dialog></>;
}
