import { env } from 'cloudflare:workers';
export function database(): D1Database { if(!env.DB) throw new Error('Database unavailable'); return env.DB; }
export const uid=()=>crypto.randomUUID();
export const query=(sql:string,...args:any[])=>database().prepare(sql).bind(...args);
export const one=async(sql:string,...args:any[])=>await query(sql,...args).first<any>();
export const rows=async(sql:string,...args:any[])=>(await query(sql,...args).all<any>()).results;
export const run=async(sql:string,...args:any[])=>await query(sql,...args).run();
export function fail(message:string,status=400):never { throw Object.assign(new Error(message),{status}); }
export const clean=(v:any,max=2000)=>typeof v==='string'?v.trim().slice(0,max):'';
export function required(v:any,max=2000) { const s=clean(v,max); if(!s)fail('Please complete all required fields.');return s; }
export function whole(v:any,min=1,max=31536000) { const n=Number(v); if(!Number.isSafeInteger(n)||n<min||n>max)fail('Enter a valid whole number within the allowed range.');return n; }
export async function hash(value:string) { return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))).map(x=>x.toString(16).padStart(2,'0')).join(''); }
export function secret() { return Array.from(crypto.getRandomValues(new Uint8Array(32))).map(x=>x.toString(16).padStart(2,'0')).join(''); }
export async function password(value:string,salt=secret()) { const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(value),'PBKDF2',false,['deriveBits']); const out=await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(salt),iterations:100000,hash:'SHA-256'},key,256); return salt+':'+Array.from(new Uint8Array(out)).map(x=>x.toString(16).padStart(2,'0')).join(''); }
export function equal(a:string,b:string) {let n=a.length^b.length; for(let i=0;i<Math.max(a.length,b.length);i++)n|=(a.charCodeAt(i)||0)^(b.charCodeAt(i)||0);return n===0;}
export async function actor(req:Request) { const token=req.headers.get('authorization')?.match(/^Bearer ([a-f0-9]{64})$/)?.[1] || req.headers.get('cookie')?.match(/(?:^|;\s*)tb_session=([^;]+)/)?.[1]; if(!token)fail('Please sign in to continue.',401);const u=await one('SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.id=? AND s.expires>unixepoch()',await hash(token));if(!u)fail('Please sign in again.',401);if(u.suspended)fail('Your account is suspended. Contact the community administrator.',403);return u; }
export async function rate(req:Request,key:string,max=12) {const ip=req.headers.get('cf-connecting-ip')||'local';const k=await hash(ip+':'+key);await run('INSERT INTO rate_limits(id,count,expires) VALUES(?,1,unixepoch()+900) ON CONFLICT(id) DO UPDATE SET count=CASE WHEN expires<unixepoch() THEN 1 ELSE count+1 END, expires=CASE WHEN expires<unixepoch() THEN unixepoch()+900 ELSE expires END',k);const r=await one('SELECT count FROM rate_limits WHERE id=?',k);if(r.count>max)fail('Too many attempts. Please wait 15 minutes before trying again.',429);}
export function publicUser(u:any) {if(!u)return null;const {password,recovery,...safe}=u;return safe;}
export async function profile(id:string,self=false) {const u=await one(`SELECT id,name,location,skills,preferences,image,created_at ${self?',email,role,suspended,phone,language,age_band,account_type':''} FROM users WHERE id=?`,id);if(!u)fail('Member not found.',404);return {...u,organizations:await rows("SELECT o.id,o.public_name,o.legal_name,(o.status='verified' AND o.review_due>unixepoch()) AS verified FROM organizations o JOIN organization_members m ON m.organization_id=o.id WHERE m.user_id=? AND m.active=1 AND o.status='verified' AND o.review_due>unixepoch()",id),...await one('SELECT AVG(rating) AS rating, COUNT(*) AS review_count FROM reviews WHERE recipient_id=?',id),...await one("SELECT COUNT(*) AS completed_tasks, COALESCE(SUM(CASE WHEN helper_id=? THEN actual_seconds ELSE 0 END),0) AS contributed, COALESCE(SUM(CASE WHEN requester_id=? THEN actual_seconds ELSE 0 END),0) AS received FROM tasks WHERE status='completed' AND (requester_id=? OR helper_id=?)",id,id,id,id),reviews:await rows('SELECT r.*,u.name AS author_name FROM reviews r JOIN users u ON u.id=r.author_id WHERE recipient_id=? ORDER BY r.created_at DESC LIMIT 30',id)};}
export async function balance(id:string){return await one('SELECT * FROM balances WHERE user_id=?',id);}
export const taskSelect=`SELECT t.*, (SELECT p.title FROM partner_task_links l JOIN partner_programs p ON p.id=l.required_training_id WHERE l.task_id=t.id) AS training_title, (SELECT p.organization_id FROM partner_task_links l JOIN partner_programs p ON p.id=l.program_id WHERE l.task_id=t.id) AS partner_organization_id, (SELECT COALESCE(NULLIF(o.public_name,''),o.legal_name) FROM organizations o JOIN organization_members m ON m.organization_id=o.id WHERE m.user_id=t.requester_id AND r.account_type='organization' AND m.active=1 AND o.status='verified' AND o.review_due>unixepoch() LIMIT 1) AS verified_partner, c.name AS category, r.name AS requester_name,r.image AS requester_image,h.name AS helper_name,(SELECT AVG(rating) FROM reviews WHERE recipient_id=t.requester_id) AS requester_rating,(SELECT COUNT(*) FROM reviews WHERE recipient_id=t.requester_id) AS requester_reviews FROM tasks t JOIN users r ON r.id=t.requester_id JOIN categories c ON c.id=t.category_id LEFT JOIN users h ON h.id=t.helper_id`;
export async function task(id:string,u:any){const t=await one(taskSelect+' WHERE t.id=?',id);if(!t)fail('Task not found.',404);if(t.status!=='open'&&t.requester_id!==u.id&&t.helper_id!==u.id&&u.role!=='admin')fail('This task is private to its participants.',403);return t;}
export function participant(t:any,u:any) {if(t.requester_id!==u.id&&t.helper_id!==u.id)fail('Only task participants can do this.',403);}
export function admin(u:any){if(u.role!=='admin')fail('Administrator access required.',403);}
export function money(s:number){const m=Math.floor(s/60);return `${Math.floor(m/60)}h ${m%60}m${s%60?` ${s%60}s`:''}`;}
