// Geographic reference data from country-state-city 3.2.1; see THIRD_PARTY_NOTICES.md.
import source from './geography.json?raw';
const data=JSON.parse(source) as {countries:{isoCode:string,name:string,flag:string}[],regions:Record<string,{isoCode:string,name:string}[]>,cities:Record<string,string[]>};
export const countries=data.countries;
export function regions(country:string){return data.regions[country]||[];}
export function cities(country:string,state:string){return (state?data.cities[`${country}/${state}`]||[]:Object.entries(data.cities).filter(([key])=>key.startsWith(country+'/')).flatMap(([,names])=>names)).map(name=>({name}));}
export function communityLabel(country:string,state:string,city:string){const c=countries.find(x=>x.isoCode===country);const s=regions(country).find(x=>x.isoCode===state);if(!c||(regions(country).length&&!s))return '';const options=cities(country,state);if(options.length&&!options.some(x=>x.name===city))return '';return [c.name,s?.name,options.length?city:null].filter(Boolean).join(' / ');}
export function parseCommunity(label:string){const [countryName,stateName,cityName]=label.split(' / ');const c=countries.find(x=>x.name===countryName);if(!c){const normalize=(v:string)=>v.trim().toLocaleLowerCase().replace(/\s+/g,' ');const key=normalize(label);if(key){const hits:{country:string,state:string,city:string}[]=[];for(const country of countries){for(const state of regions(country.isoCode)){const towns=cities(country.isoCode,state.isoCode);if(!towns.length&&normalize(state.name)===key)hits.push({country:country.isoCode,state:state.isoCode,city:''});for(const town of towns)if(normalize(town.name)===key)hits.push({country:country.isoCode,state:state.isoCode,city:town.name});}}if(hits.length===1)return hits[0];}return {country:'',state:'',city:''};}const s=regions(c.isoCode).find(x=>x.name===stateName);return {country:c.isoCode,state:s?.isoCode||'',city:s?cityName||'':stateName||''};}
export function validCommunity(label:string){const p=parseCommunity(label);return !!label&&communityLabel(p.country,p.state,p.city)===label;}
