import {env} from 'cloudflare:workers';
import {one,rows,query,database,run,fail,required,clean,whole,uid,secret,hash,admin} from './bank';

export const states=['incomplete','submitted','under_review','additional_information','verified','unable_to_verify'];
export async function verificationPolicy(){return {
 minimumAge:Number((await one("SELECT value FROM settings WHERE id='minimum_age'"))?.value??14),
 reviewDays:Number((await one("SELECT value FROM settings WHERE id='organization_review_days'"))?.value??365),
 jurisdictions:await rows('SELECT * FROM verification_policies ORDER BY jurisdiction')
};}
export function dateOfBirth(value:any){const s=required(value,10);const d=new Date(s+'T00:00:00Z');if(!/^\d{4}-\d{2}-\d{2}$/.test(s)||!Number.isFinite(+d)||d.toISOString().slice(0,10)!==s||s>new Date().toISOString().slice(0,10)||Number(s.slice(0,4))<1900)fail('Enter a valid date of birth.');return s;}
export function oldEnough(dob:string,age:number){const now=new Date();const cutoff=new Date(Date.UTC(now.getUTCFullYear()-age,now.getUTCMonth(),now.getUTCDate()));return dob<=cutoff.toISOString().slice(0,10);}
export function ageBandFromBirth(dob:string){const today=new Date();let age=today.getUTCFullYear()-Number(dob.slice(0,4));if(today.toISOString().slice(5,10)<dob.slice(5))age--;return age<18?'under18':age<25?'18-24':age<35?'25-34':age<45?'35-44':age<55?'45-54':age<65?'55-64':age<75?'65-74':'75plus';}
export function organizationFields(b:any){const email=(v:any)=>{const e=required(v,254).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e))fail('Enter valid organization email addresses.');return e;};const website=clean(b.website,500);if(website){let url;try{url=new URL(website)}catch{fail('Use a full HTTPS website address.')}if(url.protocol!=='https:')fail('Use a full HTTPS website address.');}return [required(b.legalName,200),clean(b.publicName,200),required(b.jurisdiction,100).toUpperCase(),required(b.entityType,100),required(b.registrationId,150).toUpperCase(),required(b.registeredAddress,600),website,email(b.contactEmail),required(b.contactPhone,50),required(b.mission,2000),required(b.representativeName,100),required(b.representativeRole,100),email(b.representativeEmail)];}
const orgColumns='legal_name,public_name,jurisdiction,entity_type,registration_id,registered_address,website,contact_email,contact_phone,mission,representative_name,representative_role,representative_email';
export function createOrganization(b:any,userId:string){const id=uid();return [query(`INSERT INTO organizations(id,${orgColumns}) VALUES(${Array(14).fill('?').join(',')})`,id,...organizationFields(b)),query("INSERT INTO organization_members(id,organization_id,user_id,role) VALUES(?,?,?,'owner')",uid(),id,userId)];}
export async function verificationSummary(u:any){const v=await one('SELECT status,age_eligible,duplicate_status,verified_at,feedback FROM identity_verifications WHERE user_id=?',u.id);return {accountType:u.account_type,identity:v||{status:'incomplete',age_eligible:0,duplicate_status:'pending'},canParticipate:u.role==='admin'||(u.account_type==='individual'&&v?.status==='verified'&&v.age_eligible===1&&v.duplicate_status==='clear')||Boolean(u.account_type==='organization'&&await one("SELECT o.id FROM organizations o JOIN organization_members m ON m.organization_id=o.id WHERE m.user_id=? AND m.active=1 AND m.role IN ('owner','program_manager') AND o.status='verified' AND o.review_due>unixepoch()",u.id)),organizations:await rows('SELECT o.id,o.public_name,o.legal_name,o.status,o.review_due,m.role FROM organizations o JOIN organization_members m ON m.organization_id=o.id WHERE m.user_id=? AND m.active=1',u.id)};}
export async function requireParticipation(u:any){if(!(await verificationSummary(u)).canParticipate)fail(u.account_type==='organization'?'Your organization needs current verification and an owner or program manager role to start new tasks.':'Complete age and identity verification before starting new requests or accepting tasks.',403);}
async function member(u:any,id:string,owner=false){const m=await one('SELECT * FROM organization_members WHERE organization_id=? AND user_id=? AND active=1',id,u.id);if(!m||(owner&&m.role!=='owner'))fail('Organization access is not available for this account.',403);return m;}
const audit=(u:any,action:string,target:string,reason:string)=>query('INSERT INTO admin_actions(id,actor_id,action,target_id,reason) VALUES(?,?,?,?,?)',uid(),u.id,action,target,reason);
const yes=(v:any)=>v===true||v==='on';
export async function verificationRoute(u:any,id:string|undefined,b:any,post:boolean){
 if(id==='policy'&&!post)return verificationPolicy();
 if(!id&&!post)return {summary:await verificationSummary(u),policy:await verificationPolicy(),individual:await one('SELECT legal_name,birth_date,status,feedback,version FROM identity_verifications WHERE user_id=?',u.id),messages:await rows('SELECT m.id,m.content,m.created_at,u.name AS sender_name FROM verification_messages m JOIN users u ON u.id=m.sender_id WHERE m.user_id=? AND m.organization_id IS NULL ORDER BY m.created_at LIMIT 100',u.id)};
 if(id==='individual'&&post){if(u.account_type!=='individual')fail('Use your organization application.',403);const dob=dateOfBirth(b.birthDate),policy=await verificationPolicy();if(!oldEnough(dob,policy.minimumAge))fail(`You must be at least ${policy.minimumAge} to participate.`);const existing=await one('SELECT * FROM identity_verifications WHERE user_id=?',u.id);if(existing?.status==='verified')fail('Contact verification staff to correct verified identity details.',409);await run("INSERT INTO identity_verifications(user_id,legal_name,birth_date,status) VALUES(?,?,?,'submitted') ON CONFLICT(user_id) DO UPDATE SET legal_name=excluded.legal_name,birth_date=excluded.birth_date,status='submitted',age_eligible=0,duplicate_status='pending',version=identity_verifications.version+1",u.id,required(b.legalName,100),dob);return {ok:true};}
 if(id==='message'&&post){let target=u.id,org=clean(b.organizationId,100)||null;if(org)await member(u,org);await run('INSERT INTO verification_messages(id,user_id,organization_id,sender_id,content) VALUES(?,?,?,?,?)',uid(),target,org,u.id,required(b.content,2000));return {ok:true};}
 if(id==='organization'){
  const orgId=required(b.organizationId,100);const m=await member(u,orgId,post);const o=await one('SELECT * FROM organizations WHERE id=?',orgId);
  if(post){if(Number(b.version)!==o.version)fail('This application changed. Refresh before submitting.',409);const fields=organizationFields(b);await database().batch([query(`UPDATE organizations SET ${orgColumns.split(',').map(c=>c+'=?').join(',')},status='submitted',registry_checked=0,representative_checked=0,activity_checked=0,version=version+1 WHERE id=? AND version=?`,...fields,orgId,whole(b.version,0)),audit(u,'organization_resubmitted',orgId,'Organization details submitted for review')]);}
  const application=await one('SELECT * FROM organizations WHERE id=?',orgId);const {evidence_reference,reviewer_id,...visible}=application;return {organization:visible,role:m.role,members:await rows('SELECT m.user_id,m.role,u.name FROM organization_members m JOIN users u ON u.id=m.user_id WHERE m.organization_id=? AND m.active=1',orgId),messages:await rows('SELECT m.content,m.created_at,u.name AS sender_name FROM verification_messages m JOIN users u ON u.id=m.sender_id WHERE m.organization_id=? ORDER BY m.created_at LIMIT 100',orgId),capabilities:organizationCapabilities(application,m.role)};
 }
 if(id==='invite'&&post){const orgId=required(b.organizationId);await member(u,orgId,true);const org=await one('SELECT * FROM organizations WHERE id=?',orgId);if(org.status!=='verified'||org.review_due<=Date.now()/1000)fail('Organization verification must be current before inviting staff.',403);if(!['program_manager','training_manager','staff'].includes(b.role))fail('Choose a staff role.');const email=required(b.email,254).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))fail('Enter a valid email.');if(await one("SELECT m.id FROM organization_members m JOIN users u ON u.id=m.user_id WHERE m.organization_id=? AND u.email=? AND m.role='owner'",orgId,email))fail('The organization owner already has access.',409);const token=secret();await database().batch([query('INSERT INTO organization_invites(id,organization_id,email,role,expires,invited_by) VALUES(?,?,?,?,unixepoch()+604800,?)',await hash(token),orgId,email,b.role,u.id),audit(u,'organization_invite',orgId,'Staff invitation created')]);return {inviteToken:token};}
 if(id==='accept-invite'&&post){const key=await hash(required(b.token,100)),invite=await one('SELECT i.* FROM organization_invites i JOIN organizations o ON o.id=i.organization_id WHERE i.id=? AND i.email=? AND i.accepted_by IS NULL AND i.expires>unixepoch() AND o.status=\'verified\' AND o.review_due>unixepoch()',key,u.email);if(!invite)fail('This invitation is unavailable for your account.',403);await database().batch([query('INSERT INTO organization_members(id,organization_id,user_id,role) SELECT ?,organization_id,?,role FROM organization_invites WHERE id=? AND accepted_by IS NULL ON CONFLICT(organization_id,user_id) DO UPDATE SET role=excluded.role,active=1 WHERE organization_members.role<>\'owner\'',uid(),u.id,key),query('UPDATE organization_invites SET accepted_by=? WHERE id=? AND accepted_by IS NULL',u.id,key),audit(u,'organization_invite_accepted',invite.organization_id,'Staff member accepted invitation')]);return {ok:true};}
 if(id==='remove-member'&&post){await member(u,required(b.organizationId),true);if(b.userId===u.id)fail('The owner cannot remove their own access.');await database().batch([query("UPDATE organization_members SET active=0 WHERE organization_id=? AND user_id=? AND role<>'owner'",b.organizationId,required(b.userId)),audit(u,'organization_member_removed',b.organizationId,'Owner revoked staff access')]);return {ok:true};}
 if(id==='review-queue'){admin(u);if(post)fail('Method not allowed.',405);return {individuals:await rows('SELECT v.user_id,v.legal_name,v.birth_date,v.status,v.age_eligible,v.duplicate_status,v.method,v.evidence_reference,v.reviewer_id,v.verified_at,v.feedback,v.version,u.email FROM identity_verifications v JOIN users u ON u.id=v.user_id ORDER BY v.rowid DESC LIMIT 200'),organizations:await rows('SELECT * FROM organizations ORDER BY created_at DESC LIMIT 200'),policy:await verificationPolicy()};}
 if(id==='review-messages'){admin(u);return rows('SELECT m.content,m.created_at,u.name AS sender_name FROM verification_messages m JOIN users u ON u.id=m.sender_id WHERE '+(b.organizationId?'m.organization_id=?':'m.user_id=? AND m.organization_id IS NULL')+' ORDER BY m.created_at LIMIT 100',required(b.organizationId||b.userId));}
 if(id==='review'&&post){admin(u);const reason=required(b.reason,2000),status=required(b.status,50);if(!states.includes(status)||status==='incomplete'||status==='submitted')fail('Choose a review decision.');const policy=await verificationPolicy();const org=!!b.organizationId;const target=required(b.organizationId||b.userId,100);const current=await one(org?'SELECT * FROM organizations WHERE id=?':'SELECT * FROM identity_verifications WHERE user_id=?',target);if(!current)fail('Application not found.',404);if(!org&&target===u.id||org&&await one('SELECT id FROM organization_members WHERE organization_id=? AND user_id=?',target,u.id))fail('You cannot verify your own account or organization.',403);if(Number(b.version)!==current.version)fail('This application changed. Refresh before reviewing.',409);if(status==='verified'&&current.status!=='under_review')fail('Start a review before approving the application.',409);
  let statement;
  if(org){const rule=await one('SELECT * FROM verification_policies WHERE jurisdiction=?',current.jurisdiction);if(status==='verified'&&(!yes(b.registryChecked)||!yes(b.representativeChecked)||!rule||rule.activity_required&&!yes(b.activityChecked)))fail('Complete the jurisdiction requirements, registry check and representative authorization check.');statement=query('UPDATE organizations SET status=?,registry_checked=?,representative_checked=?,activity_checked=?,evidence_reference=?,feedback=?,reviewer_id=?,verified_at=?,review_due=?,version=version+1 WHERE id=? AND version=?',status,yes(b.registryChecked)?1:0,yes(b.representativeChecked)?1:0,yes(b.activityChecked)?1:0,status==='verified'?required(b.evidenceReference,2000):clean(b.evidenceReference,2000),reason,u.id,status==='verified'?Math.floor(Date.now()/1000):null,status==='verified'?Math.floor(Date.now()/1000)+policy.reviewDays*86400:null,target,current.version);
  }else{let identityKey=current.identity_key,dup=current.duplicate_status;const eligible=current.birth_date&&oldEnough(current.birth_date,policy.minimumAge);if(status==='verified'){
    if(!eligible||!yes(b.ageChecked)||!yes(b.identityChecked)||!yes(b.duplicateChecked))fail('Verify the original identity, age eligibility and duplicate check first.');
    // A keyed fingerprint of a reviewer-checked issuer + stable identity identifier. Raw identifiers are never persisted.
    const pepper=(env as any).VERIFICATION_HASH_KEY;if(!pepper)fail('The administrator must configure the private verification hashing key before approving individuals.',503);
    const canonical=required(b.identityIssuer,100).normalize('NFKC').toUpperCase().replace(/\s+/g,'')+'|'+required(b.identityIdentifier,200).normalize('NFKC').toUpperCase().replace(/[\s-]+/g,'');
    const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(pepper),{name:'HMAC',hash:'SHA-256'},false,['sign']);identityKey=Array.from(new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(canonical)))).map(n=>n.toString(16).padStart(2,'0')).join('');
    if(await one('SELECT user_id FROM identity_verifications WHERE identity_key=? AND user_id<>?',identityKey,target)){await database().batch([query("UPDATE identity_verifications SET status='under_review',duplicate_status='review',feedback='Further identity review is needed. Contact verification staff or use account recovery.',version=version+1 WHERE user_id=? AND version=?",target,current.version),audit(u,'identity_duplicate_review',target,'Possible duplicate identity; no second approval or credit issued')]);return {ok:true,reviewRequired:true};}dup='clear';
  }
  statement=query('UPDATE identity_verifications SET status=?,age_eligible=?,identity_key=?,duplicate_status=?,method=?,evidence_reference=?,reviewer_id=?,verified_at=?,feedback=?,version=version+1 WHERE user_id=? AND version=?',status,status==='verified'?1:0,identityKey,dup,'manual_in_person',status==='verified'?required(b.evidenceReference,2000):clean(b.evidenceReference,2000),u.id,status==='verified'?Math.floor(Date.now()/1000):null,reason,target,current.version);}
  const result=await database().batch([statement,audit(u,org?'organization_review':'identity_review',target,reason)]);if(!result[0].meta.changes)fail('Application changed. Refresh and review again.',409);return {ok:true};
 }
 if(id==='review-reply'&&post){admin(u);const target=required(b.userId||u.id),org=clean(b.organizationId)||null;await database().batch([query('INSERT INTO verification_messages(id,user_id,organization_id,sender_id,content) VALUES(?,?,?,?,?)',uid(),target,org,u.id,required(b.content,2000)),audit(u,'verification_reply',org||target,'Verification staff replied')]);return {ok:true};}
 if(id==='policy'&&post){admin(u);const min=whole(b.minimumAge,1,120),days=whole(b.reviewDays,1,3650),reason=required(b.reason);await database().batch([query("INSERT INTO settings(id,value) VALUES('minimum_age',?) ON CONFLICT(id) DO UPDATE SET value=excluded.value",String(min)),query("INSERT INTO settings(id,value) VALUES('organization_review_days',?) ON CONFLICT(id) DO UPDATE SET value=excluded.value",String(days)),query("UPDATE identity_verifications SET status='under_review',age_eligible=0,feedback='Age policy changed; a new review is required.',version=version+1 WHERE status='verified' AND birth_date>date('now',?)",'-'+min+' years'),audit(u,'verification_policy','settings',reason)]);return {ok:true};}
 if(id==='jurisdiction'&&post){admin(u);await database().batch([query('INSERT INTO verification_policies(jurisdiction,identifier_label,documents,activity_required) VALUES(?,?,?,?) ON CONFLICT(jurisdiction) DO UPDATE SET identifier_label=excluded.identifier_label,documents=excluded.documents,activity_required=excluded.activity_required',required(b.jurisdiction,100).toUpperCase(),required(b.identifierLabel,200),required(b.documents,2000),yes(b.activityRequired)?1:0),audit(u,'verification_jurisdiction',b.jurisdiction,required(b.reason))]);return {ok:true};}
 fail('Verification action not found.',404);
}
export function organizationCapabilities(o:any,role:string){const verified=o?.status==='verified'&&o.review_due>Date.now()/1000;return {verified,manageStaff:verified&&role==='owner',managePrograms:verified&&['owner','program_manager'].includes(role),manageTraining:verified&&['owner','training_manager'].includes(role),viewInsights:verified&&['owner','program_manager'].includes(role)};}
