import { sqliteTable, text, integer, index, uniqueIndex } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';
const id = () => text('id').primaryKey();
const created = () => integer('created_at').notNull().default(sql`(unixepoch())`);
export const users = sqliteTable('users', {
 id:id(), email:text('email').notNull().unique(), name:text('name').notNull(), password:text('password').notNull(), recovery:text('recovery').notNull(),
 location:text('location').notNull().default(''), phone:text('phone').notNull().default(''), language:text('language').notNull().default('en'), ageBand:text('age_band').notNull().default(''), skills:text('skills').notNull().default(''), preferences:text('preferences').notNull().default(''), image:text('image'),
 role:text('role').notNull().default('member'), suspended:integer('suspended').notNull().default(0), createdAt:created()
});
export const sessions=sqliteTable('sessions',{id:id(), userId:text('user_id').notNull().references(()=>users.id), expires:integer('expires').notNull()},t=>[index('sessions_user').on(t.userId)]);
export const limits=sqliteTable('rate_limits',{id:id(), count:integer('count').notNull(), expires:integer('expires').notNull()});
export const settings=sqliteTable('settings',{id:id(), value:text('value').notNull()});
export const categories=sqliteTable('categories',{id:id(), name:text('name').notNull().unique(), active:integer('active').notNull().default(1)});
export const tasks=sqliteTable('tasks',{
 id:id(), requesterId:text('requester_id').notNull().references(()=>users.id), helperId:text('helper_id').references(()=>users.id), title:text('title').notNull(), description:text('description').notNull(), categoryId:text('category_id').notNull().references(()=>categories.id), location:text('location').notNull(), remote:integer('remote').notNull(), estimatedSeconds:integer('estimated_seconds').notNull(), requestedAt:integer('requested_at').notNull(), status:text('status').notNull().default('open'), requesterAgreed:integer('requester_agreed').notNull().default(0), helperAgreed:integer('helper_agreed').notNull().default(0), requesterReady:integer('requester_ready').notNull().default(0), helperReady:integer('helper_ready').notNull().default(0), startedAt:integer('started_at'), finishedAt:integer('finished_at'), actualSeconds:integer('actual_seconds'), finishedBy:text('finished_by').references(()=>users.id), confirmedBy:text('confirmed_by').references(()=>users.id), confirmedAt:integer('confirmed_at'), problem:text('problem'), createdAt:created()
},t=>[index('tasks_discovery').on(t.status,t.requestedAt),index('tasks_requester').on(t.requesterId),index('tasks_helper').on(t.helperId)]);
export const ledger=sqliteTable('ledger',{
 id:id(), sourceId:text('source_id').references(()=>users.id), destinationId:text('destination_id').references(()=>users.id), taskId:text('task_id').references(()=>tasks.id), amount:integer('amount').notNull(), type:text('type').notNull(), status:text('status').notNull().default('posted'), actorId:text('actor_id').references(()=>users.id), metadata:text('metadata').notNull(), createdAt:created()
},t=>[index('ledger_source').on(t.sourceId,t.createdAt),index('ledger_destination').on(t.destinationId,t.createdAt),uniqueIndex('ledger_task_type').on(t.taskId,t.type),uniqueIndex('ledger_onboarding_once').on(t.destinationId).where(sql`${t.type} = 'onboarding'`)]);
export const reviews=sqliteTable('reviews',{id:id(),taskId:text('task_id').notNull().references(()=>tasks.id),authorId:text('author_id').notNull().references(()=>users.id),recipientId:text('recipient_id').notNull().references(()=>users.id),rating:integer('rating').notNull(),feedback:text('feedback').notNull(),createdAt:created()},t=>[uniqueIndex('review_once').on(t.taskId,t.authorId),index('reviews_recipient').on(t.recipientId)]);
export const messages=sqliteTable('messages',{id:id(),taskId:text('task_id').notNull().references(()=>tasks.id),senderId:text('sender_id').notNull().references(()=>users.id),content:text('content').notNull(),photo:text('photo'),createdAt:created()},t=>[index('messages_task').on(t.taskId,t.createdAt)]);
export const notifications=sqliteTable('notifications',{id:id(),userId:text('user_id').notNull().references(()=>users.id),taskId:text('task_id').references(()=>tasks.id),text:text('text').notNull(),readAt:integer('read_at'),createdAt:created()},t=>[index('notifications_user').on(t.userId,t.createdAt)]);
export const audit=sqliteTable('admin_actions',{id:id(),actorId:text('actor_id').notNull().references(()=>users.id),action:text('action').notNull(),targetId:text('target_id').notNull(),reason:text('reason').notNull(),createdAt:created()});

export const consents=sqliteTable('agreement_acceptances',{id:id(),userId:text('user_id').notNull().references(()=>users.id),taskId:text('task_id').references(()=>tasks.id),kind:text('kind').notNull(),version:text('version').notNull(),signature:text('signature').notNull(),signatureDrawing:text('signature_drawing'),acceptedAt:integer('accepted_at').notNull().default(sql`(unixepoch())`)},t=>[uniqueIndex('consent_account_once').on(t.userId,t.kind,t.version).where(sql`${t.taskId} IS NULL`),uniqueIndex('consent_task_once').on(t.userId,t.taskId,t.kind,t.version).where(sql`${t.taskId} IS NOT NULL`)]);
export const assistanceEvents=sqliteTable('assistance_events',{id:id(),userId:text('user_id').notNull().references(()=>users.id),kind:text('kind').notNull(),status:text('status').notNull(),model:text('model').notNull(),tokens:integer('tokens').notNull().default(0),createdAt:created()},t=>[index('assistance_time').on(t.createdAt)]);
export const reviewFlags=sqliteTable('review_flags',{id:id(),rule:text('rule').notNull(),subject:text('subject').notNull(),evidence:text('evidence').notNull(),status:text('status').notNull().default('review_recommended'),reason:text('reason'),reviewerId:text('reviewer_id').references(()=>users.id),reviewedAt:integer('reviewed_at'),createdAt:created()},t=>[uniqueIndex('flag_rule_subject').on(t.rule,t.subject)]);
export const taskEvents=sqliteTable('task_events',{id:id(),taskId:text('task_id').notNull().references(()=>tasks.id),status:text('status').notNull(),actorId:text('actor_id').references(()=>users.id),note:text('note'),createdAt:created()},t=>[index('task_events_task').on(t.taskId,t.createdAt)]);
export const matchingPreferences=sqliteTable('matching_preferences',{userId:text('user_id').primaryKey().references(()=>users.id),mode:text('mode').notNull().default('any'),days:text('days').notNull().default('[]'),timezone:text('timezone').notNull().default('UTC'),maxMinutes:integer('max_minutes')});
export const taskInquiryMessages = sqliteTable('task_inquiry_messages', {
 id:id(), taskId:text('task_id').notNull().references(()=>tasks.id), visitorId:text('visitor_id').notNull().references(()=>users.id), senderId:text('sender_id').notNull().references(()=>users.id), content:text('content').notNull(), photo:text('photo'), createdAt:created()
}, t=>[index('inquiry_thread').on(t.taskId,t.visitorId,t.createdAt)]);
